// ────────────────────────────────────────────────────────────────
// 实验室 — 轻量级自动驾驶前沿研究课题
// 聚焦：低数据量 · 低计算资源 · 可个人复现
// ────────────────────────────────────────────────────────────────

// ═══════════════════════════════════════════════════════════════
// 研究方向分类
// ═══════════════════════════════════════════════════════════════
export const LAB_CATEGORIES = [
  { id: 'all',        label: '全部',           icon: '🔬', color: '#6c5ce7' },
  { id: 'nerf',       label: '神经辐射场',     icon: '🌐', color: '#00cec9' },
  { id: 'occ',        label: '占用网络',       icon: '🧊', color: '#fd79a8' },
  { id: 'diffusion',  label: '扩散模型',       icon: '🌊', color: '#ffa657' },
  { id: 'distill',    label: '知识蒸馏',       icon: '🧪', color: '#3fb950' },
  { id: 'few-shot',   label: '小样本学习',     icon: '🎯', color: '#79c0ff' },
  { id: 'sim',        label: '仿真 & 生成',    icon: '🎮', color: '#d2a8ff' },
  { id: 'data-synth', label: '数据合成',       icon: '🧫', color: '#e17055' },
];

// ═══════════════════════════════════════════════════════════════
// 研究课题
// ═══════════════════════════════════════════════════════════════
export const LAB_PROJECTS = [
  // ─── 1. NeRF 场景重建 ───
  {
    id: 'streetgaussian',
    title: 'Street Gaussians：动态街景 3D 高斯重建',
    category: 'nerf',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 3090 / 4090',
    dataReq: 'nuScenes mini (10 场景) 或自采视频',
    trainTime: '~30 min / 场景',
    status: 'ready',
    tags: ['3D Gaussian Splatting', 'Dynamic Scene', 'Novel View'],
    desc: '将 3D Gaussian Splatting 应用于动态街景重建。分离静态背景和动态物体（车辆/行人），支持新视角合成和时间插值。相比 NeRF 训练快 100x，渲染快 1000x。',
    whyLightweight: '3DGS 训练极快（30min vs NeRF 数小时），nuScenes mini 仅 10 个场景 ~3GB，单卡即可运行。',
    keyIdea: '将每个高斯点附加时间属性，静态高斯固定不动，动态高斯随时间变形。用 LiDAR 点云初始化高斯位置，大幅加速收敛。',
    steps: [
      { name: '数据准备', desc: '下载 nuScenes mini，提取 6 路相机图像 + LiDAR 点云 + 位姿', time: '~10 min' },
      { name: '点云初始化', desc: 'LiDAR 点云 → 初始高斯点位置 + 颜色', time: '~2 min' },
      { name: '静态场景训练', desc: '固定背景高斯，优化位置/颜色/协方差', time: '~15 min' },
      { name: '动态物体分离', desc: '3D 检测框内的高斯标记为动态，添加时间变形', time: '~10 min' },
      { name: '联合优化', desc: '静态 + 动态高斯联合训练，渲染损失 + 深度损失', time: '~15 min' },
      { name: '新视角渲染', desc: '任意视角实时渲染 (>100 FPS)，导出视频', time: '实时' },
    ],
    papers: ['3D Gaussian Splatting (SIGGRAPH 2023)', 'Street Gaussians (ECCV 2024)', 'DrivingGaussian (CVPR 2024)'],
    codeRef: 'https://github.com/zju3dv/street_gaussians',
    color: '#00cec9',
  },
  {
    id: 'emernerf',
    title: 'EmerNeRF：自监督动态场景 NeRF',
    category: 'nerf',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 3090',
    dataReq: 'Waymo Open 5 场景 或 nuScenes mini',
    trainTime: '~2 hr / 场景',
    status: 'ready',
    tags: ['NeRF', 'Self-Supervised', 'Scene Flow', 'Emerald'],
    desc: '无需 3D 标注的自监督动态 NeRF。自动分解静态/动态场景，学习场景流（Scene Flow），支持 4D 时空重建。关键创新：Emergence of Spatial-Temporal Decomposition。',
    whyLightweight: '自监督无需标注数据，5 个场景即可训练出高质量结果。单卡 3090 可运行，训练 2 小时。',
    keyIdea: '用哈希编码加速 NeRF，通过光流一致性自监督学习场景流，自动涌现静态/动态分解能力。',
    steps: [
      { name: '数据准备', desc: '提取多帧图像 + 相机位姿 + LiDAR (可选)', time: '~15 min' },
      { name: '静态 NeRF 预训练', desc: '先训练静态场景 NeRF 作为初始化', time: '~40 min' },
      { name: '场景流学习', desc: '引入时间维度，学习每个点的运动向量', time: '~40 min' },
      { name: '动态分解', desc: '根据场景流大小自动分离静态/动态区域', time: '~30 min' },
      { name: '评估 & 可视化', desc: 'PSNR/SSIM 评估 + 新视角渲染 + 场景流可视化', time: '~10 min' },
    ],
    papers: ['EmerNeRF (ICLR 2024)', 'Instant-NGP (SIGGRAPH 2022)', 'NSF (NeurIPS 2019)'],
    codeRef: 'https://github.com/NVlabs/EmerNeRF',
    color: '#00cec9',
  },

  // ─── 2. 占用网络 ───
  {
    id: 'surroundocc',
    title: 'SurroundOcc：纯视觉 3D 占用预测',
    category: 'occ',
    difficulty: '⭐⭐',
    computeReq: '1×RTX 3090 (FP16)',
    dataReq: 'nuScenes mini + Occ3D 标注',
    trainTime: '~4 hr (mini set)',
    status: 'ready',
    tags: ['Occupancy', 'Vision-Only', 'BEV', '3D Semantic'],
    desc: '仅用 6 路环视相机预测 3D 占用网格（200×200×16），无需 LiDAR。核心：2D→3D 特征提升 + 多尺度占用解码。在 Occ3D 基准上 mIoU 达 34.7%。',
    whyLightweight: 'nuScenes mini 仅 10 场景，Occ3D 提供现成标注。FP16 训练单卡 3090 可跑，4 小时出结果。',
    keyIdea: '2D 图像特征通过 Spatial Cross-Attention 提升到 3D 体素空间，多尺度 3D 卷积解码占用概率。',
    steps: [
      { name: '数据准备', desc: '下载 nuScenes mini + Occ3D 占用标注', time: '~20 min' },
      { name: 'BEV 特征提取', desc: 'ResNet-50 + FPN → 2D 多尺度特征', time: '配置' },
      { name: '2D→3D 提升', desc: 'Spatial Cross-Attention 将 2D 特征投影到 3D 体素', time: '~2 hr' },
      { name: '占用解码', desc: '3D UNet 解码 → 200×200×16 占用网格 (17 类)', time: '~2 hr' },
      { name: '评估', desc: 'mIoU / IoU per class / 可视化 3D 占用', time: '~15 min' },
    ],
    papers: ['SurroundOcc (ICCV 2023)', 'Occ3D (NeurIPS 2023)', 'FlashOcc (AAAI 2024)'],
    codeRef: 'https://github.com/weiyithu/SurroundOcc',
    color: '#fd79a8',
  },
  {
    id: 'occ-distill',
    title: 'LiDAR→Camera 占用蒸馏',
    category: 'occ',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 4090',
    dataReq: 'nuScenes mini + LiDAR 占用伪标签',
    trainTime: '~6 hr',
    status: 'ready',
    tags: ['Distillation', 'Occupancy', 'Cross-Modal', 'Teacher-Student'],
    desc: '用 LiDAR 占用模型（教师）蒸馏纯视觉占用模型（学生）。学生模型部署时不需要 LiDAR，但性能接近多模态融合。研究跨模态知识迁移的核心问题。',
    whyLightweight: '教师模型可用预训练权重，只需训练学生模型。nuScenes mini 足够验证蒸馏效果。',
    keyIdea: 'BEV 特征蒸馏 + 体素级 KL 散度 + 关系蒸馏（保持空间结构一致性）。',
    steps: [
      { name: '教师模型', desc: '加载预训练 LiDAR 占用模型，生成 soft label', time: '~30 min' },
      { name: '学生模型搭建', desc: '纯视觉 BEV → 3D 占用，轻量化设计', time: '配置' },
      { name: 'BEV 蒸馏', desc: '教师 BEV 特征 → 学生 BEV 特征 (MSE Loss)', time: '~2 hr' },
      { name: '体素蒸馏', desc: '教师占用概率 → 学生占用概率 (KL Divergence)', time: '~2 hr' },
      { name: '关系蒸馏', desc: '保持体素间空间关系一致性', time: '~1.5 hr' },
      { name: '评估对比', desc: '学生 vs 教师 vs 纯视觉 baseline 的 mIoU 对比', time: '~15 min' },
    ],
    papers: ['BEVDistill (ICLR 2023)', 'UniDistill (CVPR 2023)', 'TiG-BEV (CVPR 2023)'],
    codeRef: 'https://github.com/OpenDriveLab/BEVDistill',
    color: '#fd79a8',
  },

  // ─── 3. 扩散模型 ───
  {
    id: 'magicdrive',
    title: 'MagicDrive：可控街景生成',
    category: 'diffusion',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 4090 (24GB)',
    dataReq: 'nuScenes mini + BEV 布局',
    trainTime: '~8 hr (LoRA 微调)',
    status: 'ready',
    tags: ['Diffusion', 'Controllable Generation', 'Data Augmentation', 'LoRA'],
    desc: '基于 Stable Diffusion 的可控多视角街景生成。输入 BEV 布局（车道线 + 3D 框）→ 输出逼真的 6 路环视图像。可用于数据增强，解决长尾场景数据不足问题。',
    whyLightweight: '基于预训练 SD 1.5，LoRA 微调仅需 ~100MB 显存增量。nuScenes mini 的 BEV 布局作为条件输入。',
    keyIdea: 'BEV 布局编码为 ControlNet 条件，多视角一致性通过 Cross-View Attention 保证。LoRA 微调 SD 适配街景域。',
    steps: [
      { name: '数据准备', desc: 'nuScenes → BEV 布局渲染（车道线 + 3D 框 + 语义）', time: '~30 min' },
      { name: 'SD 加载', desc: '加载 Stable Diffusion 1.5 预训练权重', time: '~5 min' },
      { name: 'ControlNet 训练', desc: 'BEV 布局 → ControlNet 条件编码', time: '~3 hr' },
      { name: 'LoRA 微调', desc: '街景域适配，rank=16，仅训练 ~4M 参数', time: '~4 hr' },
      { name: '多视角生成', desc: '输入 BEV 布局 → 生成 6 路一致环视图像', time: '~10s/组' },
      { name: '数据增强评估', desc: '生成数据加入训练 → 检测 mAP 提升评估', time: '~2 hr' },
    ],
    papers: ['MagicDrive (ICLR 2024)', 'BEVGen (ICCV 2023)', 'DriveDreamer (ECCV 2024)'],
    codeRef: 'https://github.com/cure-lab/MagicDrive',
    color: '#ffa657',
  },
  {
    id: 'gaia1-mini',
    title: 'GAIA-1 Mini：轻量世界模型视频预测',
    category: 'diffusion',
    difficulty: '⭐⭐⭐⭐',
    computeReq: '1×RTX 4090',
    dataReq: 'nuScenes mini 视频序列',
    trainTime: '~12 hr',
    status: 'experimental',
    tags: ['World Model', 'Video Prediction', 'Autoregressive', 'VQ-VAE'],
    desc: '复现 Wayve GAIA-1 的轻量版本：VQ-VAE 编码驾驶视频 → Transformer 自回归预测未来帧 → 解码为视频。探索世界模型在自动驾驶中的核心范式。',
    whyLightweight: '缩小模型规模（128d latent, 6 层 Transformer），nuScenes mini 视频序列足够训练 mini 版本。重点理解架构而非追求 SOTA。',
    keyIdea: 'VQ-VAE 将视频帧压缩为离散 token → GPT-like Transformer 预测下一帧 token → VQ-VAE 解码器还原视频。',
    steps: [
      { name: '数据准备', desc: 'nuScenes 前视相机视频序列，裁剪为 256×256', time: '~15 min' },
      { name: 'VQ-VAE 训练', desc: '图像 → 16×16 离散 token (codebook=512)', time: '~4 hr' },
      { name: 'Transformer 训练', desc: '自回归预测下一帧 token 序列', time: '~6 hr' },
      { name: '条件生成', desc: '加入动作条件（转向/油门）控制生成', time: '~2 hr' },
      { name: '视频生成', desc: '给定初始帧 → 自回归生成未来 10 帧', time: '~5s/序列' },
      { name: '评估', desc: 'FVD / SSIM / 人工评估生成质量', time: '~30 min' },
    ],
    papers: ['GAIA-1 (Wayve 2023)', 'VideoGPT (2021)', 'Genie 2 (DeepMind 2024)'],
    codeRef: 'https://github.com/CompVis/taming-transformers',
    color: '#ffa657',
  },

  // ─── 4. 知识蒸馏 ───
  {
    id: 'bev-distill',
    title: 'BEV 感知模型蒸馏：大模型→车端小模型',
    category: 'distill',
    difficulty: '⭐⭐',
    computeReq: '1×RTX 3090',
    dataReq: 'nuScenes mini',
    trainTime: '~3 hr',
    status: 'ready',
    tags: ['Distillation', 'BEV', 'Model Compression', 'Edge Deploy'],
    desc: '将大型 BEV 感知模型（BEVFormer-Large）蒸馏到轻量模型（BEVFormer-Tiny），实现车端部署。研究特征蒸馏 vs Logit 蒸馏 vs 关系蒸馏的效果差异。',
    whyLightweight: '教师模型用预训练权重，学生模型参数量仅 1/10。nuScenes mini 足够做蒸馏实验。',
    keyIdea: '多层 BEV 特征对齐 + 检测头 Logit 蒸馏 + 注意力图迁移。学生模型 NDS 从 35.2 提升到 42.8（+7.6）。',
    steps: [
      { name: '教师模型', desc: '加载 BEVFormer-Base 预训练权重', time: '~5 min' },
      { name: '学生模型', desc: '搭建 BEVFormer-Tiny (ResNet-18, 2 层 Transformer)', time: '配置' },
      { name: '特征蒸馏', desc: 'BEV 特征图 L2 对齐', time: '~1 hr' },
      { name: 'Logit 蒸馏', desc: '检测头输出 KL 散度', time: '~1 hr' },
      { name: '关系蒸馏', desc: 'BEV 空间关系矩阵对齐', time: '~1 hr' },
      { name: '对比评估', desc: '学生 vs 教师 vs 无蒸馏 baseline', time: '~15 min' },
    ],
    papers: ['BEVDistill (ICLR 2023)', 'FitNets (ICLR 2015)', 'CRD (ICLR 2020)'],
    codeRef: 'https://github.com/OpenDriveLab/BEVDistill',
    color: '#3fb950',
  },

  // ─── 5. 小样本学习 ───
  {
    id: 'clip-ad',
    title: 'CLIP 零样本/少样本驾驶场景理解',
    category: 'few-shot',
    difficulty: '⭐⭐',
    computeReq: '1×RTX 3090 (推理为主)',
    dataReq: 'nuScenes mini + 自定义文本提示',
    trainTime: '~1 hr (Prompt Tuning)',
    status: 'ready',
    tags: ['CLIP', 'Zero-Shot', 'Prompt Tuning', 'Scene Understanding'],
    desc: '利用 CLIP 的视觉-语言对齐能力，实现零样本/少样本的驾驶场景分类、天气识别、危险检测。无需大量标注数据，仅通过文本提示即可完成多种感知任务。',
    whyLightweight: 'CLIP 推理不需要训练，Prompt Tuning 仅优化几个可学习 token（~1K 参数）。nuScenes mini 图像即可。',
    keyIdea: '设计驾驶场景专用的文本提示模板，如 "a photo of {scene} driving scenario"。Prompt Tuning 学习最优提示向量。',
    steps: [
      { name: '加载 CLIP', desc: 'CLIP ViT-L/14 预训练模型', time: '~2 min' },
      { name: '零样本分类', desc: '设计文本提示 → 场景/天气/时间分类', time: '~10 min' },
      { name: '零样本检测', desc: '文本提示 "a car" / "a pedestrian" → 区域匹配', time: '~10 min' },
      { name: 'Prompt Tuning', desc: '学习 4 个可学习 token，少量标注数据微调', time: '~1 hr' },
      { name: '危险场景检测', desc: '"dangerous driving scenario" 提示 → 异常检测', time: '~10 min' },
      { name: '评估', desc: '零样本 vs 少样本 vs 全监督 的精度对比', time: '~15 min' },
    ],
    papers: ['CLIP (ICML 2021)', 'CoOp (IJCV 2022)', 'CLIP-AD (CVPR 2024)'],
    codeRef: 'https://github.com/openai/CLIP',
    color: '#79c0ff',
  },
  {
    id: 'language-drive',
    title: '语言指令驱动的轨迹规划',
    category: 'few-shot',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 3090',
    dataReq: 'DriveLM 子集 (~5K 条)',
    trainTime: '~4 hr',
    status: 'ready',
    tags: ['Language Grounding', 'Trajectory Planning', 'VLA-Lite', 'DriveLM'],
    desc: '用自然语言指令（"在下个路口左转"）控制轨迹规划。轻量版 VLA：冻结 CLIP 视觉编码器 + 小型 LLM (Phi-2 2.7B) + MLP 轨迹解码头。',
    whyLightweight: 'Phi-2 仅 2.7B 参数，冻结视觉编码器只训练投影层和轨迹头。DriveLM 5K 条语言标注足够。',
    keyIdea: '视觉特征 + 语言指令 → 跨模态融合 → 未来 3s 轨迹点序列。核心是学习语言到动作的映射。',
    steps: [
      { name: '数据准备', desc: 'DriveLM 子集：图像 + 语言指令 + GT 轨迹', time: '~15 min' },
      { name: '视觉编码', desc: 'CLIP ViT-L 提取图像特征 (冻结)', time: '配置' },
      { name: '语言编码', desc: 'Phi-2 编码语言指令 (冻结 + LoRA)', time: '配置' },
      { name: '融合训练', desc: 'MLP Projector + 轨迹解码头训练', time: '~3 hr' },
      { name: '指令测试', desc: '输入不同语言指令 → 观察轨迹变化', time: '~30 min' },
      { name: '评估', desc: 'L2 误差 / 碰撞率 / 指令遵循率', time: '~30 min' },
    ],
    papers: ['DriveLM (ECCV 2024)', 'LMDrive (CVPR 2024)', 'DriveVLM (CoRL 2024)'],
    codeRef: 'https://github.com/OpenDriveLab/DriveLM',
    color: '#79c0ff',
  },

  // ─── 6. 仿真 & 生成 ───
  {
    id: 'lidar-gen',
    title: 'LiDAR 点云生成与补全',
    category: 'sim',
    difficulty: '⭐⭐',
    computeReq: '1×RTX 3090',
    dataReq: 'nuScenes mini LiDAR 扫描',
    trainTime: '~3 hr',
    status: 'ready',
    tags: ['Point Cloud', 'Generation', 'VAE', 'Completion'],
    desc: '训练 VAE/Diffusion 模型生成逼真的 LiDAR 点云扫描，或补全稀疏点云。可用于数据增强和仿真环境构建。',
    whyLightweight: 'LiDAR 点云数据量小（每帧 ~300K 点），VAE 模型参数量小。nuScenes mini 的 LiDAR 数据足够。',
    keyIdea: '将 LiDAR 扫描转为 Range Image (64×1024) → 2D 卷积 VAE 编码/解码 → 还原为 3D 点云。',
    steps: [
      { name: '数据准备', desc: 'nuScenes LiDAR → Range Image 转换', time: '~10 min' },
      { name: 'VAE 训练', desc: 'Range Image VAE (编码器 + 解码器)', time: '~2 hr' },
      { name: '生成采样', desc: '从隐空间采样 → 生成新的 LiDAR 扫描', time: '~1s/帧' },
      { name: '点云补全', desc: '输入稀疏点云 → 编码 → 解码为稠密点云', time: '~1 hr' },
      { name: '评估', desc: 'Chamfer Distance / Earth Mover Distance', time: '~15 min' },
    ],
    papers: ['LiDARGen (CVPR 2023)', 'RangeNet++ (IROS 2019)', 'UltraLiDAR (CVPR 2023)'],
    codeRef: 'https://github.com/vzyrianov/LiDARGen',
    color: '#d2a8ff',
  },
  {
    id: 'carla-rl',
    title: 'CARLA 强化学习自动驾驶',
    category: 'sim',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 3090 + 8GB RAM',
    dataReq: '无需真实数据 (CARLA 仿真)',
    trainTime: '~6 hr (1M steps)',
    status: 'ready',
    tags: ['RL', 'CARLA', 'PPO', 'Sim-to-Real', 'End-to-End'],
    desc: '在 CARLA 仿真器中用 PPO 训练端到端自动驾驶策略。输入：前视相机图像 + 速度 → 输出：转向/油门/刹车。零真实数据，纯仿真训练。',
    whyLightweight: 'CARLA 免费开源，无需真实数据。PPO 训练 1M 步约 6 小时。模型可以很小（ResNet-18 + MLP）。',
    keyIdea: '图像 → CNN 特征 → MLP 策略网络 → 连续动作空间 (转向, 油门)。奖励函数：速度 + 车道保持 - 碰撞 - 偏离。',
    steps: [
      { name: '环境搭建', desc: '安装 CARLA 0.9.15 + Gym 接口', time: '~30 min' },
      { name: '奖励设计', desc: '速度奖励 + 车道保持 + 碰撞惩罚 + 红灯惩罚', time: '设计' },
      { name: 'PPO 训练', desc: 'ResNet-18 + MLP, 1M 步, 4 并行环境', time: '~6 hr' },
      { name: '评估', desc: '成功率 / 碰撞率 / 平均速度 / 路线完成率', time: '~1 hr' },
      { name: '可视化', desc: '录制驾驶视频 + 注意力热力图', time: '~30 min' },
      { name: '消融实验', desc: '不同奖励函数 / 网络结构 / 训练步数对比', time: '~6 hr' },
    ],
    papers: ['Learning to Drive (CoRL 2019)', 'CARLA Benchmark (CoRL 2017)', 'PPO (arXiv 2017)'],
    codeRef: 'https://github.com/carla-simulator/carla',
    color: '#d2a8ff',
  },

  // ─── 7. 数据合成 ───
  {
    id: 'vlm-auto-label',
    title: 'VLM 自动标注：零人工 3D 标注生成',
    category: 'data-synth',
    difficulty: '⭐⭐',
    computeReq: '1×RTX 3090',
    dataReq: 'nuScenes mini (10 场景)',
    trainTime: '~2 hr (推理为主)',
    status: 'ready',
    tags: ['VLM', 'Auto-Label', 'Grounded-SAM', 'InternVL', '3D Annotation'],
    desc: '利用视觉大模型（VLM）自动生成 3D 检测框和语义分割标注，完全替代人工标注。核心流程：InternVL 场景理解 → Grounded-SAM2 实例分割 → 深度估计 → 2D→3D 提升生成 3D 框。',
    whyLightweight: '全部使用预训练模型推理，无需训练。nuScenes mini 10 个场景即可验证标注质量。单卡 3090 可运行所有推理。',
    keyIdea: 'VLM 提供开放词汇检测能力 → SAM2 精确分割 → Metric3D 单目深度估计 → 几何投影生成 3D 框。与人工标注对比评估质量。',
    steps: [
      { name: '场景理解', desc: 'InternVL-Chat 描述场景内容，提取目标类别列表', time: '~10 min' },
      { name: '开放词汇检测', desc: 'Grounding-DINO 根据文本提示检测所有目标', time: '~15 min' },
      { name: '实例分割', desc: 'SAM2 对每个检测框生成精确 mask', time: '~15 min' },
      { name: '深度估计', desc: 'Metric3D / ZoeDepth 估计每像素深度', time: '~20 min' },
      { name: '2D→3D 提升', desc: 'mask + 深度 + 相机内外参 → 3D 检测框', time: '~30 min' },
      { name: '质量评估', desc: '与 nuScenes GT 对比: mAP / NDS / 类别分布', time: '~30 min' },
    ],
    papers: ['Grounded-SAM (2024)', 'InternVL (CVPR 2024)', 'Metric3D v2 (ICLR 2024)', 'SAM2 (Meta 2024)'],
    codeRef: 'https://github.com/IDEA-Research/Grounded-SAM-2',
    color: '#e17055',
  },
  {
    id: 'longtail-synth',
    title: '长尾场景定向合成：指令式街景编辑',
    category: 'data-synth',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 4090 (24GB)',
    dataReq: 'nuScenes mini + 预训练 SD/ControlNet',
    trainTime: '~6 hr (LoRA 微调)',
    status: 'ready',
    tags: ['InstructPix2Pix', 'ControlNet', 'Long-Tail', 'Data Augmentation', 'Weather Synthesis'],
    desc: '通过自然语言指令编辑真实驾驶图像，定向生成长尾稀有场景。例如："把晴天改成暴雨"、"在路边添加施工区"、"把白天改成夜间"。ControlNet 保持场景几何结构，InstructPix2Pix 根据指令修改目标属性。',
    whyLightweight: '基于预训练 SD 1.5 + ControlNet，LoRA 微调仅需训练 ~4M 参数。nuScenes mini 图像作为编辑源。单卡 4090 可运行。',
    keyIdea: 'ControlNet 提取深度/边缘条件保持结构 → InstructPix2Pix 根据文本指令编辑图像内容 → LoRA 微调适配驾驶场景域。支持链式编辑（先改天气再加物体）。',
    steps: [
      { name: '数据准备', desc: 'nuScenes mini 图像 + 深度图/边缘图提取', time: '~20 min' },
      { name: 'ControlNet 加载', desc: '加载预训练 ControlNet (depth/canny) 权重', time: '~5 min' },
      { name: 'LoRA 微调', desc: '驾驶场景域适配，rank=16，~4M 参数', time: '~4 hr' },
      { name: '天气编辑', desc: '"make it rainy/snowy/foggy" → 天气变换', time: '~10s/张' },
      { name: '物体编辑', desc: '"add construction zone" → 添加长尾物体', time: '~10s/张' },
      { name: '数据增强评估', desc: '编辑数据加入训练 → 长尾场景 mAP 提升评估', time: '~2 hr' },
    ],
    papers: ['InstructPix2Pix (CVPR 2023)', 'ControlNet (ICCV 2023)', 'DriveEditor (ECCV 2024)', 'GeoDiffusion (ICLR 2024)'],
    codeRef: 'https://github.com/timothybrooks/instruct-pix2pix',
    color: '#e17055',
  },
  {
    id: 'text2bev-scene',
    title: '文本→BEV 场景布局生成',
    category: 'data-synth',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 3090',
    dataReq: 'nuScenes mini + GPT-4 API',
    trainTime: '~4 hr',
    status: 'ready',
    tags: ['LLM', 'Scene Generation', 'BEV Layout', 'ChatScene', 'Text-to-Scene'],
    desc: '用 LLM 将自然语言场景描述解析为结构化 BEV 布局（物体位置/朝向/类别），再用 Transformer Decoder 生成合理的场景布局。支持多样性采样，同一描述生成多种合理布局。可与 MagicDrive 联合渲染为多视角图像。',
    whyLightweight: 'LLM 用 API 调用（GPT-4/Claude），Transformer Decoder 参数量小（~20M）。nuScenes mini 的 BEV 标注作为训练数据。',
    keyIdea: 'LLM 解析文本 → 结构化场景描述（JSON）→ Transformer Decoder 自回归生成物体序列（类别, x, y, θ, w, l）→ 碰撞检测 + 车道合规过滤。',
    steps: [
      { name: '数据准备', desc: 'nuScenes BEV 标注 → 物体序列 + 场景描述文本', time: '~30 min' },
      { name: 'LLM 解析', desc: 'GPT-4 将自然语言 → 结构化场景 JSON', time: '~10 min' },
      { name: 'Decoder 训练', desc: 'Transformer Decoder 学习物体序列生成', time: '~3 hr' },
      { name: '条件生成', desc: '输入场景描述 → 生成多种合理 BEV 布局', time: '~1s/场景' },
      { name: '合规过滤', desc: '碰撞检测 + 车道合规 + 物理约束过滤', time: '~5 min' },
      { name: '联合渲染', desc: 'BEV 布局 → MagicDrive → 多视角图像 (可选)', time: '~10s/组' },
    ],
    papers: ['ChatScene (CVPR 2024)', 'LCTGen (CVPR 2024)', 'SceneDiffuser (CVPR 2024)', 'BEVGen (ICCV 2023)'],
    codeRef: 'https://github.com/chat-scene/ChatScene',
    color: '#e17055',
  },
  {
    id: 'sim2real-transfer',
    title: 'Sim-to-Real 风格迁移：仿真→真实域适配',
    category: 'data-synth',
    difficulty: '⭐⭐',
    computeReq: '1×RTX 3090',
    dataReq: 'CARLA 渲染图 + nuScenes mini 真实图',
    trainTime: '~4 hr',
    status: 'ready',
    tags: ['CycleGAN', 'CUT', 'Sim-to-Real', 'Domain Adaptation', 'Style Transfer'],
    desc: '将 CARLA 仿真器渲染的图像转换为真实风格，使仿真数据可直接用于真实场景模型训练。CUT 用对比学习实现高效单向翻译，PatchNCE Loss 保持局部结构一致性。相比 CycleGAN 训练更快、效果更好。',
    whyLightweight: 'CUT 模型参数量小（~15M），单向翻译无需配对数据。CARLA 免费生成无限仿真图，nuScenes mini 提供真实域参考。单卡 3090 训练 4 小时。',
    keyIdea: 'CARLA 渲染图 → CUT Generator → 真实风格图像。PatchNCE Loss 在特征空间做对比学习，正样本=同位置 patch，负样本=不同位置 patch。保持内容不变，只迁移风格。',
    steps: [
      { name: '数据准备', desc: 'CARLA 渲染 1000 张 + nuScenes mini 1000 张 (无需配对)', time: '~30 min' },
      { name: 'CUT 训练', desc: 'Generator + PatchNCE Loss + GAN Loss', time: '~3 hr' },
      { name: '风格迁移', desc: 'CARLA 图 → 真实风格图，批量转换', time: '~5s/张' },
      { name: '质量评估', desc: 'FID / KID / LPIPS 评估迁移质量', time: '~15 min' },
      { name: '下游验证', desc: '迁移后数据训练检测模型 → mAP 对比', time: '~2 hr' },
      { name: 'CycleGAN 对比', desc: 'CUT vs CycleGAN 效果/速度/稳定性对比', time: '~4 hr' },
    ],
    papers: ['CUT (ECCV 2020)', 'CycleGAN (ICCV 2017)', 'FDA (CVPR 2020)', 'DACS (WACV 2021)'],
    codeRef: 'https://github.com/taesungp/contrastive-unpaired-translation',
    color: '#e17055',
  },
  {
    id: 'diffusion-trajectory',
    title: '扩散轨迹合成：多样化驾驶轨迹生成',
    category: 'data-synth',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 3090',
    dataReq: 'nuScenes mini 轨迹数据',
    trainTime: '~3 hr',
    status: 'ready',
    tags: ['Diffusion', 'Trajectory', 'CTG++', 'Planning', 'Constraint Guidance'],
    desc: '用扩散模型在轨迹空间扩散/去噪，条件注入地图和周围 Agent 特征，采样时生成多条多样化驾驶轨迹。支持可行性过滤（碰撞检测 + 车道合规 + 运动学约束），生成的轨迹可直接用于规划模型训练数据增强。',
    whyLightweight: '轨迹数据维度低（12×2=24d），扩散模型参数量小（~5M）。nuScenes mini 轨迹数据足够训练。单卡 3090 训练 3 小时。',
    keyIdea: 'DDPM 在轨迹空间 (T×2) 做扩散/去噪 → VectorNet 编码地图 + Agent 特征作为条件 → Classifier-Free Guidance 控制生成 → 后处理过滤不可行轨迹。',
    steps: [
      { name: '数据准备', desc: 'nuScenes 提取 ego 轨迹 + 地图 + Agent 状态', time: '~15 min' },
      { name: '条件编码', desc: 'VectorNet 编码地图多段线 + Agent 历史轨迹', time: '配置' },
      { name: 'DDPM 训练', desc: '轨迹空间扩散模型，条件注入 (Cross-Attention)', time: '~2 hr' },
      { name: '多样化采样', desc: '同一场景采样 K=10 条不同轨迹', time: '~0.5s/组' },
      { name: '可行性过滤', desc: '碰撞检测 + 车道合规 + 曲率/加速度约束', time: '~5 min' },
      { name: '规划增强评估', desc: '合成轨迹加入训练 → L2/碰撞率/舒适度对比', time: '~1 hr' },
    ],
    papers: ['CTG++ (CoRL 2023)', 'Diffusion Planner (CVPR 2024)', 'MotionDiffuser (ICLR 2024)', 'TrafficGen (ICRA 2023)'],
    codeRef: 'https://github.com/NVlabs/CTG',
    color: '#e17055',
  },

  {
    id: 'gaussianlss-bev-perception',
    title: 'GaussianLSS：高斯深度不确定性BEV感知',
    category: 'nerf',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 4090 (24GB) 或 1×RTX 3090 (24GB，需降 batch)',
    dataReq: 'nuScenes mini / nuScenes full',
    trainTime: '~45 min/epoch（单卡 3090，batch=2）',
    status: 'ready',
    tags: ["3DGS", "BEV感知", "深度估计", "CVPR2025", "nuScenes"],
    desc: 'GaussianLSS 将 3D Gaussian Splatting 引入 BEV 感知管线，以深度均值+方差对每个像素进行不确定性建模，替代传统 Lift-Splat-Shoot 中的硬深度投影。通过在 nuScenes 上的实验证明，即使输入稀疏视角图像，也能实现鲁棒的 BEV 特征聚合与 3D 目标检测。代码基于 PyTorch 2.0 + CUDA 11.8，官方仓库已开源训练/推理脚本，支持单卡复现。',
    whyLightweight: 'Gaussian 概率投影避免密集 3D 网格卷积，单卡训练显存峰值约 18GB，ResNet-50 骨干网络轻量高效。',
    papers: ["Toward Real-world BEV Perception: Depth Uncertainty Estimation via Gaussian Splatting (CVPR 2025)"],
    codeRef: 'https://github.com/Tshino118/GaussianLSS',
    color: '#4F8EF7',
  },

  {
    id: 'dualdiff-driving-scene-gen',
    title: 'DualDiff：双分支扩散驾驶场景生成',
    category: 'diffusion',
    difficulty: '⭐⭐⭐',
    computeReq: '1×RTX 3090 (24GB)，LoRA 微调模式',
    dataReq: 'nuScenes（含标注 BEV box + 语义地图）',
    trainTime: '~50 min（LoRA 微调阶段，batch=1，20 epochs）',
    status: 'ready',
    tags: ["扩散模型", "多视角生成", "数据增强", "ICRA2025", "ControlNet"],
    desc: 'DualDiff 提出前景/背景双分支条件扩散架构，通过占用射线采样（ORS）编码 3D 空间几何先验，配合语义融合注意力（SFA）实现多摄像头环视视频一致性生成。在 nuScenes 上相比 MagicDrive 等基线提升 4.09% FID，并显著改善自动驾驶感知模型在稀有场景下的泛化性。代码已在 GitHub 开源，支持 LoRA 微调以适配单卡环境。',
    whyLightweight: '冻结 Stable Diffusion 主干仅训练 ControlNet 分支，LoRA 模式下显存需求降至 ~18GB，适合单卡 3090 复现。',
    papers: ["DualDiff: Enhancing Mode Capture in Low-Dimensional Diffusion Models via Dual-Denoising (ICRA 2025)"],
    codeRef: 'https://github.com/yangzhaojason/DualDiff',
    color: '#E8673A',
  },
];

// ═══════════════════════════════════════════════════════════════
// 资源需求汇总
// ═══════════════════════════════════════════════════════════════
export const RESOURCE_SUMMARY = {
  minGPU: 'RTX 3090 (24GB)',
  recommendGPU: 'RTX 4090 (24GB)',
  minRAM: '32 GB',
  minDisk: '100 GB SSD',
  datasets: [
    { name: 'nuScenes mini', size: '~3 GB', scenes: 10, download: 'https://www.nuscenes.org/nuscenes#download' },
    { name: 'Occ3D 标注', size: '~500 MB', scenes: 10, download: 'https://github.com/Tsinghua-MARS-Lab/Occ3D' },
    { name: 'DriveLM 子集', size: '~2 GB', scenes: '5K 条', download: 'https://github.com/OpenDriveLab/DriveLM' },
    { name: 'CARLA 仿真器', size: '~15 GB', scenes: '无限生成', download: 'https://carla.org/download/' },
    { name: 'SD 1.5 + ControlNet', size: '~10 GB', scenes: '预训练权重', download: 'https://huggingface.co/runwayml/stable-diffusion-v1-5' },
  ],
  frameworks: [
    { name: 'PyTorch 2.x', role: '深度学习框架' },
    { name: 'mmdet3d', role: '3D 检测/BEV 工具箱' },
    { name: 'nerfstudio', role: 'NeRF/3DGS 训练框架' },
    { name: 'diffusers', role: 'Diffusion 模型库' },
    { name: 'stable-baselines3', role: 'RL 算法库' },
    { name: 'Grounded-SAM-2', role: 'VLM 自动标注' },
    { name: 'InternVL', role: '视觉语言理解' },
  ],
};