// ═══════════════════════════════════════════════════════════════
// 平台产品团队未来规划 — 数据定义
// ═══════════════════════════════════════════════════════════════

// 1. AI Coding & Agent 时代下的软件行业困境
export const INDUSTRY_CRISIS = {
  title: 'AI Coding & Agent 时代的软件行业困境',
  subtitle: '当 AI 能写 80% 的代码，软件团队的价值锚点在哪里？',
  timeline: [
    { year: '2022', event: 'GitHub Copilot 发布', impact: '代码补全效率 +55%', icon: '🚀', color: '#79c0ff' },
    { year: '2023', event: 'GPT-4 + Cursor 爆发', impact: '初级开发任务被替代 30%+', icon: '⚡', color: '#ffa657' },
    { year: '2024', event: 'Devin / SWE-Agent / OpenHands', impact: 'AI Agent 独立完成 Issue → PR', icon: '🤖', color: '#e17055' },
    { year: '2025', event: 'Claude Code / Codex / Gemini CLI', impact: '端到端自主编码 Agent 成熟', icon: '🧠', color: '#6c5ce7' },
    { year: '2026+', event: 'Multi-Agent 协作 + 自我进化', impact: '软件开发范式根本性重构', icon: '🌐', color: '#3fb950' },
  ],
  crises: [
    {
      id: 'commoditization',
      name: '代码商品化',
      icon: '📉',
      color: '#e17055',
      severity: '🔴 致命',
      desc: '当 AI 能在几分钟内生成高质量代码，"写代码"本身不再是稀缺能力。传统按人天计费的外包/项目制模式面临崩塌。',
      evidence: [
        'Cursor + Claude 组合可在 30 分钟内完成过去 3 天的 CRUD 开发',
        'Devin 在 SWE-bench 上解决 13.86% 的真实 GitHub Issue（2024）→ 2025 年已超 40%',
        'Google 内部 25%+ 新代码由 AI 生成（2025 Q1 财报披露）',
        'Meta 报告 AI 辅助代码审查覆盖率达 50%+',
      ],
      affected: ['外包公司', '初级开发者', '标准化 SaaS', '低复杂度项目团队'],
    },
    {
      id: 'talent_shift',
      name: '人才结构断裂',
      icon: '👥',
      color: '#ffa657',
      severity: '🔴 致命',
      desc: '初级岗位需求骤降，但高级架构师/AI 工程师严重短缺。传统"初级→中级→高级"的成长路径被打断。',
      evidence: [
        '2025 年全球科技公司初级开发岗位招聘量同比下降 35%（LinkedIn 数据）',
        'AI/ML 工程师薪资涨幅 25%+，传统后端开发薪资持平或下降',
        '大量中级开发者面临"向上突破难、向下被替代"的夹心困境',
        'Prompt Engineering 从热门岗位到被 Agent 自动化，生命周期不到 2 年',
      ],
      affected: ['初级开发者', '培训机构', '传统 IT 教育', '人力外包'],
    },
    {
      id: 'value_erosion',
      name: '产品价值侵蚀',
      icon: '💸',
      color: '#fd79a8',
      severity: '🟡 严重',
      desc: '用户可以用 AI 快速搭建"够用"的替代品，标准化软件产品的护城河被削弱。SaaS 订阅模式面临挑战。',
      evidence: [
        '用户用 Cursor 在 2 小时内复刻简单 SaaS 产品的核心功能',
        'Vercel v0 / Bolt.new 让非技术人员也能生成可用的 Web 应用',
        'AI 生成的一次性工具替代了大量轻量级 SaaS 订阅',
        'Open Source + AI 组合进一步压缩商业软件空间',
      ],
      affected: ['轻量级 SaaS', '工具类产品', '低壁垒平台', '标准化解决方案'],
    },
    {
      id: 'complexity_explosion',
      name: '复杂度爆炸',
      icon: '🌀',
      color: '#6c5ce7',
      severity: '🟡 严重',
      desc: 'AI 生成代码的速度远超人类理解和维护的速度，系统复杂度指数级增长。技术债务积累加速。',
      evidence: [
        'AI 生成的代码缺乏统一架构思想，不同 Agent 产出的代码风格割裂',
        '代码量增长 3-5x，但可维护性下降，"AI 写的代码只有 AI 能改"',
        '安全漏洞随 AI 生成代码量线性增长（Snyk 2025 报告）',
        '测试覆盖率与代码生成速度严重脱节',
      ],
      affected: ['大型系统', '金融/医疗等高可靠性领域', '长期维护项目', '安全敏感系统'],
    },
    {
      id: 'differentiation_collapse',
      name: '差异化坍缩',
      icon: '🪞',
      color: '#00cec9',
      severity: '🟡 严重',
      desc: '当所有团队都用相同的 AI 工具，产出趋同。技术实现不再是竞争壁垒，"做什么"比"怎么做"更重要。',
      evidence: [
        '多家创业公司用 AI 在同一周内推出几乎相同的产品',
        '技术栈选型趋同（Next.js + Tailwind + Supabase 成为 AI 时代的"标准答案"）',
        'UI/UX 设计也被 AI 标准化，产品外观越来越相似',
        '竞争焦点从技术能力转向领域知识和数据壁垒',
      ],
      affected: ['技术驱动型创业公司', '通用型 SaaS', '缺乏领域壁垒的团队'],
    },
  ],
};

// 2. 全球软件行业破局思路
export const GLOBAL_BREAKOUT = {
  title: '全球软件行业破局思路',
  subtitle: '从"卖代码"到"卖决策"——价值链重构',
  lastUpdated: '2026-04',
  strategies: [
    {
      id: 'palantir',
      name: 'Palantir 模式',
      subtitle: '数据操作系统 + 前线部署',
      icon: '🏛️',
      color: '#6c5ce7',
      marketCap: '$260B+ (2025)',
      revenue: '$2.87B (2024)',
      growth: '+29% YoY',
      keyInsight: '不卖软件，卖"决策能力"。将 AI 嵌入客户的核心业务流程，成为不可替代的操作系统。',
      pillars: [
        { name: 'Ontology（本体论）', desc: '将客户的业务实体、关系、规则建模为统一的数字孪生，AI 在此之上推理', icon: '🧬' },
        { name: 'AIP（AI Platform）', desc: '让大模型直接操作业务数据和流程，而非仅仅对话。LLM → Action', icon: '⚡' },
        { name: 'Forward Deployed Engineer', desc: '工程师驻场客户，深度理解业务后定制解决方案。高触达 + 高粘性', icon: '🪖' },
        { name: 'TITAN（边缘部署）', desc: '将 AI 能力部署到战场/工厂/油田等断网环境，离线自主决策', icon: '🛡️' },
      ],
      moat: '深度业务绑定 + 数据飞轮 + 安全合规壁垒 → 客户迁移成本极高',
      signals: [
        { date: '2025-02', tag: '财报', level: 'hot', text: 'Q4 2024 商业营收 +54% YoY，Rule of 40 达 68，首次实现全年 GAAP 盈利' },
        { date: '2025-03', tag: '产品', level: 'hot', text: 'AIP for Defense 发布，将 LLM 直接接入战场指挥系统，TITAN 边缘节点量产' },
        { date: '2025-04', tag: '市场', level: 'watch', text: '欧洲商业客户增速加快，Airbus/Philips 等大客户续约并扩容，FDE 团队扩至 800+' },
        { date: '2025-04', tag: '竞争', level: 'watch', text: 'Microsoft 推 Fabric + Copilot 正面竞争 Foundry，Palantir 强调 Ontology 差异化' },
      ],
      deepDive: {
        why: 'Palantir 的核心不是技术领先，而是"业务理解深度"。FDE 驻场 6-18 个月后，客户的 Ontology 已经成为业务运转的神经系统，任何替换都意味着重建整个数字孪生。',
        risks: ['FDE 模式人力成本高，规模化难度大', '政府收入占比 55%，受政策预算波动影响大', '商业客户集中度高，前 20 客户贡献 40%+ 营收'],
        opportunities: ['AIP 将 LLM 与 Ontology 结合，打开中小企业市场', 'Agent 时代 Ontology 成为 AI 行动的"地图"，价值倍增', '国防 AI 预算持续增长，TITAN 边缘部署打开新市场'],
        watchMetrics: ['商业 NRR（目标 >120%）', '商业客户数（目标 1000+）', 'AIP 收入占比（目前 ~15%）', 'FDE 人均产出'],
      },
    },
    {
      id: 'vertical_ai',
      name: '垂直 AI 深耕',
      subtitle: '领域知识 + AI = 不可替代',
      icon: '🏥',
      color: '#3fb950',
      examples: [
        { company: 'Veeva Systems', domain: '生命科学', desc: '医药行业 CRM + 临床试验管理，FDA 合规壁垒', revenue: '$2.4B' },
        { company: 'Toast', domain: '餐饮', desc: '餐饮全链路（POS + 支付 + 供应链 + AI 排班）', revenue: '$4.0B' },
        { company: 'Procore', domain: '建筑', desc: '建筑项目管理 + AI 安全检测 + 成本预测', revenue: '$1.0B' },
        { company: 'Samsara', domain: '物联网/物流', desc: 'IoT 传感器 + AI 车队管理 + 安全评分', revenue: '$0.9B' },
        { company: 'Waymo / Momenta', domain: '自动驾驶', desc: '数据闭环 + 世界模型 + 端到端驾驶', revenue: '—' },
      ],
      keyInsight: '通用 AI 工具无法替代深度领域知识。垂直场景的数据壁垒 + 合规要求 + 行业 know-how 构成真正的护城河。',
      signals: [
        { date: '2025-03', tag: '医疗', level: 'hot', text: 'Abridge（AI 医疗记录）完成 $250M C 轮，Epic 系统集成，覆盖 500+ 医院' },
        { date: '2025-03', tag: '法律', level: 'hot', text: 'Harvey AI 估值 $3B，Allen & Overy 等顶级律所全面部署，合同审查效率提升 10x' },
        { date: '2025-04', tag: '金融', level: 'watch', text: 'Ramp（AI 财务）ARR 突破 $500M，AI 支出分析 + 自动报销成为标配' },
        { date: '2025-04', tag: '制造', level: 'watch', text: 'Sight Machine（工厂 AI）被 Rockwell Automation 收购，工业 AI 整合加速' },
      ],
      deepDive: {
        why: '垂直 AI 的护城河来自三层叠加：①行业数据（无法公开获取）②合规认证（FDA/FedRAMP/金融牌照）③工作流嵌入（替换成本 = 重新培训所有员工）。通用 LLM 能做 80% 的事，但最后 20% 的行业特殊性决定了生死。',
        risks: ['市场天花板相对较低，单一垂直难以支撑大市值', '大模型能力提升可能压缩垂直 AI 的差异化空间', '行业监管变化可能颠覆现有合规壁垒'],
        opportunities: ['医疗/法律/金融三大高价值垂直仍处于早期', 'AI Agent 让垂直 SaaS 从"工具"升级为"员工"', '出海：中国垂直 AI 在制造/供应链有独特数据优势'],
        watchMetrics: ['行业 NRR（健康垂直 >120%）', '合规认证数量', 'AI 功能渗透率', '人均 ARR（衡量 AI 杠杆）'],
      },
    },
    {
      id: 'platform_play',
      name: '平台生态战略',
      subtitle: '成为 AI Agent 的"操作系统"',
      icon: '🌐',
      color: '#ffa657',
      examples: [
        { company: 'Salesforce (Agentforce)', desc: '企业 AI Agent 平台，Agent 直接操作 CRM 数据和业务流程' },
        { company: 'ServiceNow', desc: 'IT 运维 AI Agent，自动处理工单、变更、事件响应' },
        { company: 'Databricks', desc: '数据 + AI 统一平台，从数据湖到模型训练到部署的全链路' },
        { company: 'Snowflake (Cortex)', desc: '数据云 + AI 推理，让 AI 直接在数据仓库内运行' },
      ],
      keyInsight: '不做 AI 本身，做 AI Agent 运行的基础设施。掌握数据层和工作流层，成为 Agent 时代的"水电煤"。',
      signals: [
        { date: '2025-02', tag: 'Salesforce', level: 'hot', text: 'Agentforce 发布 6 个月 ARR 突破 $1B，Marc Benioff 称"Agent 是 SaaS 的终结者"' },
        { date: '2025-03', tag: 'Databricks', level: 'hot', text: '估值 $62B，收购 Tabular（Apache Iceberg 创始团队），统一数据湖仓格局' },
        { date: '2025-04', tag: 'ServiceNow', level: 'watch', text: 'AI Agent 处理 40% 的 IT 工单无需人工介入，客户 ROI 平均 4.2x' },
        { date: '2025-04', tag: '竞争', level: 'watch', text: 'Microsoft 365 Copilot + Power Platform 形成闭环，传统平台厂商面临降维打击' },
      ],
      deepDive: {
        why: '平台战略的本质是"控制 Agent 的行动空间"。当 AI Agent 需要读写数据、触发工作流、调用 API 时，谁控制了这些接口，谁就控制了 Agent 的能力边界。Salesforce 的 Agentforce 本质上是把 CRM 数据变成 Agent 的"行动地图"。',
        risks: ['平台战略需要极强的生态号召力，中小公司难以复制', 'OpenAI/Anthropic 可能直接做企业平台，绕过中间层', 'Agent 标准化（MCP/A2A 协议）可能削弱平台锁定效应'],
        opportunities: ['MCP（Model Context Protocol）标准化后，平台价值从"连接"转向"数据质量"', '垂直平台（行业 Agent OS）比通用平台更容易建立壁垒', '中国企业微信/钉钉生态有机会成为中国版 Agentforce'],
        watchMetrics: ['Agent 数量 & 活跃度', '平台 API 调用量', '开发者生态规模', 'Agent 完成任务成功率'],
      },
    },
    {
      id: 'compound_ai',
      name: '复合 AI 系统',
      subtitle: '从单模型到多 Agent 协作系统',
      icon: '🔗',
      color: '#e17055',
      examples: [
        { company: 'Cognition (Devin)', desc: '多 Agent 协作的 AI 软件工程师，规划→编码→测试→部署' },
        { company: 'Sierra AI', desc: 'AI 客服 Agent，多轮对话 + 业务操作 + 人工升级' },
        { company: 'Harvey AI', desc: '法律 AI Agent，合同审查 + 法规检索 + 风险评估' },
        { company: 'Glean', desc: '企业知识 AI，连接所有内部系统的统一搜索和问答' },
      ],
      keyInsight: '单个 LLM 调用无法解决复杂业务问题。需要多 Agent 编排、工具调用、记忆管理、人机协作的复合系统。',
      signals: [
        { date: '2025-02', tag: 'Anthropic', level: 'hot', text: 'Claude 3.7 Sonnet 发布"扩展思考"模式，复杂推理任务成功率大幅提升，Agent 可靠性拐点出现' },
        { date: '2025-03', tag: '框架', level: 'hot', text: 'Google A2A（Agent-to-Agent）协议发布，多 Agent 协作标准化进程加速' },
        { date: '2025-03', tag: 'Coding', level: 'hot', text: 'Cursor + Claude 组合在真实工程任务中达到 Senior 工程师水平，SWE-bench 突破 70%' },
        { date: '2025-04', tag: '企业', level: 'watch', text: 'Glean 估值 $4.6B，企业知识 AI 成为 CIO 预算第一优先级，替代传统搜索' },
      ],
      deepDive: {
        why: '复合 AI 的价值在于"可靠性"而非"智能"。单个 LLM 的幻觉率 ~5%，但 10 步 Agent 链路的成功率只有 0.95^10 ≈ 60%。复合系统通过验证层、回滚机制、人工审批节点，将可靠性提升到企业可接受的水平（>95%）。',
        risks: ['Agent 可靠性仍是核心瓶颈，复杂任务失败率高', '多 Agent 系统的调试和可观测性极其困难', '安全风险：Agent 被注入攻击或执行有害操作'],
        opportunities: ['Claude 3.7 / GPT-5 的推理能力突破正在解决可靠性问题', 'MCP + A2A 协议标准化后，Agent 生态将爆发', '中国 DeepSeek R2 + 国产 Agent 框架有机会弯道超车'],
        watchMetrics: ['SWE-bench 得分（代码 Agent 基准）', 'Agent 任务完成率', '人工干预率', '平均任务完成时长'],
      },
    },
    {
      id: 'data_moat',
      name: '数据飞轮壁垒',
      subtitle: '数据 → AI → 更好的产品 → 更多数据',
      icon: '🔄',
      color: '#00cec9',
      examples: [
        { company: 'Tesla FSD', desc: '百万辆车的影子模式数据 → 训练 → OTA 更新 → 更多数据' },
        { company: 'Spotify', desc: '用户行为数据 → 推荐算法 → 更长使用时长 → 更多数据' },
        { company: 'Waze', desc: '用户导航数据 → 实时路况 → 更准确导航 → 更多用户' },
        { company: 'Scale AI', desc: '标注数据 → 更好的标注模型 → 更低成本 → 更多客户数据' },
      ],
      keyInsight: '在 AI 时代，数据是唯一不会被 AI 自动生成的稀缺资源。拥有独特数据源的公司拥有真正的护城河。',
      signals: [
        { date: '2025-02', tag: 'Tesla', level: 'hot', text: 'FSD V13 在美国无监督驾驶里程突破 10 亿英里，数据飞轮效应显现，Waymo 数据量仍差 100x' },
        { date: '2025-03', tag: '合成数据', level: 'hot', text: 'Scale AI 发布合成数据平台，真实数据 + 合成数据混合训练成为主流，数据壁垒被部分稀释' },
        { date: '2025-03', tag: '数据要素', level: 'watch', text: '中国数据要素市场化政策落地，数据交易所成交额同比 +300%，数据资产入表加速' },
        { date: '2025-04', tag: '隐私计算', level: 'watch', text: '联邦学习 + 隐私计算让"数据不动模型动"成为可能，打破数据孤岛同时保护主权' },
      ],
      deepDive: {
        why: '数据飞轮的核心不是"数据量"，而是"数据独特性"。合成数据的崛起正在稀释通用数据的价值，但行为数据（用户真实操作）、传感器数据（物理世界）、专有业务数据（内部流程）仍然无法被合成。飞轮的关键是：你的数据是否能让你的 AI 做到竞争对手做不到的事。',
        risks: ['合成数据技术成熟后，数据壁垒被大幅稀释', '数据隐私法规（GDPR/个保法）限制数据收集和使用', '大模型预训练数据趋于饱和，增量数据边际价值下降'],
        opportunities: ['物理世界数据（机器人/自动驾驶/工厂）仍极度稀缺', '中国数据要素政策为数据资产化提供制度支撑', '隐私计算让数据在不共享的前提下产生联合价值'],
        watchMetrics: ['数据独特性评分（无法被公开数据替代的比例）', '数据新鲜度（实时 vs 历史）', '数据飞轮转速（新数据→模型更新周期）', '数据变现效率（$/TB）'],
      },
    },
  ],
};

// 3. Palantir 模式深度解析
export const PALANTIR_DEEP_DIVE = {
  title: 'Palantir 模式深度解析',
  subtitle: '从"软件公司"到"决策操作系统"的范式转移',
  // 核心产品矩阵
  products: [
    {
      name: 'Foundry',
      target: '商业客户',
      icon: '🏭',
      color: '#3fb950',
      desc: '企业数据操作系统，将分散的数据源统一为可操作的数字孪生',
      layers: [
        { name: 'Data Connection', desc: '200+ 数据源连接器，实时/批量数据接入' },
        { name: 'Pipeline Builder', desc: '可视化数据流水线，代码/低代码混合编排' },
        { name: 'Ontology', desc: '业务对象建模层，定义实体/关系/动作/约束' },
        { name: 'Workshop', desc: '业务用户操作界面，拖拽式决策应用构建' },
        { name: 'AIP', desc: 'LLM 集成层，自然语言 → Ontology 操作 → 业务动作' },
      ],
    },
    {
      name: 'Gotham',
      target: '政府/国防',
      icon: '🛡️',
      color: '#6c5ce7',
      desc: '情报分析与反恐平台，处理 PB 级多源情报数据的关联分析',
      layers: [
        { name: 'Data Integration', desc: 'SIGINT/HUMINT/OSINT/GEOINT 多源情报融合' },
        { name: 'Graph Analysis', desc: '万亿级知识图谱，实体关系推理与模式发现' },
        { name: 'Gaia', desc: '地理空间分析，卫星图像 + 地面传感器 + 轨迹数据' },
        { name: 'TITAN', desc: '边缘部署，断网环境下的自主 AI 推理' },
      ],
    },
    {
      name: 'AIP',
      target: '全客户',
      icon: '⚡',
      color: '#e17055',
      desc: 'AI Platform — 让 LLM 不只是聊天，而是直接操作业务系统',
      layers: [
        { name: 'LLM Orchestration', desc: '多模型编排（GPT-4/Claude/Llama），任务路由' },
        { name: 'Ontology Grounding', desc: 'LLM 输出锚定到 Ontology 对象，消除幻觉' },
        { name: 'Action Framework', desc: 'AI 建议 → 人工审批 → 系统执行的闭环' },
        { name: 'Logic & Guardrails', desc: '业务规则引擎 + 安全护栏，确保 AI 行为合规' },
      ],
    },
  ],
  // Palantir 的核心竞争力
  moats: [
    {
      name: 'Ontology 本体论',
      icon: '🧬',
      color: '#6c5ce7',
      desc: '不是简单的数据库 Schema，而是对客户整个业务世界的数字化建模。包含实体、关系、动作、约束、权限。一旦建立，迁移成本极高。',
      analogy: '如果数据库是"存储"，Ontology 就是"理解"。AI 在 Ontology 之上推理，而非在原始数据上猜测。',
    },
    {
      name: 'Forward Deployed Engineer',
      icon: '🪖',
      color: '#e17055',
      desc: '不是远程支持，而是工程师驻场 6-18 个月，深度理解客户业务后构建解决方案。这种模式看似"不可扩展"，但创造了极高的客户粘性和 NRR（净收入留存率 >115%）。',
      analogy: '传统 SaaS 是"卖工具"，Palantir 是"派军师"。军师走了，但他建立的作战体系留下了。',
    },
    {
      name: '安全合规壁垒',
      icon: '🔒',
      color: '#3fb950',
      desc: 'FedRAMP High / IL5 / IL6 / NATO SECRET 等最高级别安全认证。获取这些认证需要数年时间和数亿美元投入，构成极高的进入壁垒。',
      analogy: '这不是技术壁垒，而是信任壁垒。在国防和情报领域，信任比技术更稀缺。',
    },
    {
      name: '数据网络效应',
      icon: '🔄',
      color: '#ffa657',
      desc: '客户使用越多，Ontology 越丰富 → AI 推理越准确 → 客户越依赖 → 更多数据接入。形成正向飞轮。',
      analogy: '每个客户的 Ontology 都是独一无二的"数字基因组"，随时间指数级增值。',
    },
  ],
  // Code as Proxy 设计哲学
  codeAsProxy: {
    title: 'Code as Proxy — 更高级的设计哲学',
    desc: 'Palantir AIP 的核心设计原则：AI 不直接操作数据，而是生成"代理代码"，让代码替 AI 去触碰数据',
    tagline: '"Don\'t give AI your data. Give AI the ability to write code that touches your data."',
    principle: 'AI 理解业务语义（Ontology），生成操作指令（Action/Code），指令在受控环境中执行，AI 只看到结果摘要——而非原始数据。这是 Palantir 解决"AI 能力 vs 数据安全"根本矛盾的核心答案。',
    why: [
      { icon: '🔒', point: '数据安全', desc: 'LLM 永远不接触原始数据，消除数据泄露的根本风险' },
      { icon: '🎯', point: '消除幻觉', desc: 'AI 操作有类型约束的 Ontology 对象，而非自由文本，幻觉率大幅降低' },
      { icon: '✅', point: '可审计', desc: '每一个 AI 生成的 Action 都可被记录、回放、审计，满足合规要求' },
      { icon: '🔄', point: '人机协作', desc: 'AI 建议 → 人工审批 → 系统执行，保留人类决策权' },
    ],
    layers: [
      { layer: '业务语义层', role: 'Ontology', desc: 'AI 理解的不是原始数据，而是业务对象（订单/用户/设备）及其关系', color: '#6c5ce7' },
      { layer: '代理生成层', role: 'Code / Action Gen', desc: 'AI 根据自然语言意图，生成操作 Ontology 的代码或结构化 Action', color: '#e17055' },
      { layer: '受控执行层', role: 'Foundry Runtime', desc: '代码在 Foundry 沙箱中执行，权限受 Ontology ACL 约束，数据不出域', color: '#0984e3' },
      { layer: '结果摘要层', role: 'Result Summary', desc: 'AI 只收到执行结果的摘要（聚合统计/状态变更），不接触原始行数据', color: '#00b894' },
    ],
    vsTraditional: {
      traditional: { label: '传统 AI 助手', flow: '用户数据 → LLM → 直接回答', risk: '数据直接暴露给 LLM' },
      proxy: { label: 'Code as Proxy', flow: 'Ontology Schema → LLM → 生成 Action → 本地执行 → 结果摘要', risk: null },
    },
    impact: '这一设计让 Palantir AIP 成为唯一能在 IL6（最高机密）环境中运行 LLM 的商业产品，也是其在政府和金融客户中无可替代的核心原因。',
  },

  // 财务数据
  financials: {
    revenue: [
      { year: '2020', value: '$1.09B', growth: '+47%' },
      { year: '2021', value: '$1.54B', growth: '+41%' },
      { year: '2022', value: '$1.91B', growth: '+24%' },
      { year: '2023', value: '$2.23B', growth: '+17%' },
      { year: '2024', value: '$2.87B', growth: '+29%' },
      { year: '2025E', value: '$3.75B', growth: '+31%' },
    ],
    metrics: {
      nrr: '>115%',
      govRevenue: '55%',
      commercialRevenue: '45%',
      commercialGrowth: '+54% YoY (2024 Q4)',
      customers: '711 (2024)',
      topCustomerConcentration: '<10%',
      ruleOf40: '68 (2024 Q4)',
    },
  },
};

// 4. 平台产品团队应对框架
export const RESPONSE_FRAMEWORK = {
  title: '平台产品团队应对框架',
  subtitle: '借鉴 Palantir 模式，构建 AI 时代的平台产品竞争力',
  // 核心理念
  philosophy: {
    before: '我们是一个写代码的团队，交付软件产品',
    after: '我们是一个构建"决策操作系统"的团队，交付业务能力',
    shift: '从 Code Factory → Decision Engine',
  },
  // 四层架构
  layers: [
    {
      id: 'data_foundation',
      name: '数据基座层',
      subtitle: 'Data Foundation',
      icon: '🏗️',
      color: '#326ce5',
      palantirRef: 'Foundry Data Connection + Pipeline',
      desc: '构建统一的数据接入、治理和服务能力，成为业务数据的"单一事实来源"',
      capabilities: [
        { name: '统一数据接入', desc: '100+ 数据源连接器，实时/批量/流式，覆盖内部系统 + 外部 API + IoT', tech: 'Kafka · Flink · Airbyte · dbt' },
        { name: '数据湖仓一体', desc: 'Iceberg 格式统一存储，支持 ACID 事务 + 时间旅行 + Schema 演进', tech: 'Iceberg · Trino · Spark · LakeFS' },
        { name: '数据质量闭环', desc: '自动化数据质量检测 + 异常告警 + 血缘追踪 + 影响分析', tech: 'Great Expectations · OpenLineage · Monte Carlo' },
        { name: '特征工程平台', desc: '离线/在线特征统一管理，特征复用率 > 60%，避免重复计算', tech: 'Feast · Tecton · Redis' },
      ],
      metrics: [
        { label: '数据源覆盖', value: '100+', unit: '个' },
        { label: '数据延迟', value: '<5', unit: 'min' },
        { label: '数据质量 SLA', value: '99.5%', unit: '' },
        { label: '特征复用率', value: '>60%', unit: '' },
      ],
    },
    {
      id: 'ontology',
      name: '业务本体层',
      subtitle: 'Business Ontology',
      icon: '🧬',
      color: '#6c5ce7',
      palantirRef: 'Foundry Ontology',
      desc: '将业务领域知识建模为结构化的本体（Ontology），让 AI 在业务语义上推理而非原始数据上猜测',
      capabilities: [
        { name: '实体建模', desc: '定义业务核心对象（用户/订单/设备/场景），属性 + 关系 + 约束', tech: 'Knowledge Graph · Neo4j · RDF' },
        { name: '业务规则引擎', desc: '将领域专家知识编码为可执行规则，AI 输出必须满足规则约束', tech: 'Drools · OPA · Custom DSL' },
        { name: '数字孪生', desc: '业务系统的实时数字镜像，支持 What-if 分析和仿真推演', tech: 'Event Sourcing · CQRS · Simulation' },
        { name: '语义搜索 & 推理', desc: '基于 Ontology 的语义检索和逻辑推理，消除 LLM 幻觉', tech: 'Milvus · LangChain · RAG + KG' },
      ],
      metrics: [
        { label: '业务实体覆盖', value: '200+', unit: '类' },
        { label: '规则库', value: '500+', unit: '条' },
        { label: 'AI 幻觉率', value: '<3%', unit: '' },
        { label: '推理准确率', value: '>95%', unit: '' },
      ],
    },
    {
      id: 'ai_platform',
      name: 'AI 平台层',
      subtitle: 'AI Platform (AIP)',
      icon: '⚡',
      color: '#e17055',
      palantirRef: 'Palantir AIP',
      desc: '让 AI 不只是"聊天"，而是直接操作业务系统。从 LLM → Action 的完整闭环',
      capabilities: [
        { name: 'Multi-Agent 编排', desc: '多 Agent 协作框架，任务分解 → 并行执行 → 结果聚合 → 人工审批', tech: 'LangGraph · CrewAI · AutoGen' },
        { name: 'Tool & API Gateway', desc: 'Agent 可调用的工具注册中心，统一鉴权 + 限流 + 审计 + 回滚', tech: 'MCP · OpenAPI · gRPC · Kong' },
        { name: '安全护栏', desc: 'AI 输出的多层校验：格式 → 业务规则 → 权限 → 人工审批 → 执行', tech: 'Guardrails AI · NeMo · Custom' },
        { name: '持续学习', desc: '用户反馈 → 模型微调 → A/B 测试 → 灰度发布的闭环', tech: 'RLHF · DPO · MLflow · Seldon' },
      ],
      metrics: [
        { label: 'Agent 任务成功率', value: '>90%', unit: '' },
        { label: '平均响应时间', value: '<3', unit: 's' },
        { label: '安全拦截率', value: '>99%', unit: '' },
        { label: '人工干预率', value: '<10%', unit: '' },
      ],
    },
    {
      id: 'decision_app',
      name: '决策应用层',
      subtitle: 'Decision Applications',
      icon: '🎯',
      color: '#3fb950',
      palantirRef: 'Foundry Workshop + AIP Copilot',
      desc: '面向业务用户的决策应用，将底层能力封装为可操作的业务工具',
      capabilities: [
        { name: 'AI Copilot', desc: '嵌入业务流程的 AI 助手，理解上下文 + 建议操作 + 一键执行', tech: 'Chat UI · Streaming · Context Window' },
        { name: '决策仪表盘', desc: '实时业务指标 + AI 异常检测 + 根因分析 + 行动建议', tech: 'Grafana · Superset · Custom Viz' },
        { name: '自动化工作流', desc: 'AI 驱动的业务流程自动化，人工只处理异常和审批', tech: 'Temporal · Airflow · n8n' },
        { name: '场景化应用', desc: '针对具体业务场景的深度定制应用（如智能排班/库存优化/风控）', tech: 'Low-Code · Plugin · Micro Frontend' },
      ],
      metrics: [
        { label: '决策效率提升', value: '5-10x', unit: '' },
        { label: '自动化率', value: '>70%', unit: '' },
        { label: '用户满意度', value: '>4.5', unit: '/5' },
        { label: '业务 ROI', value: '>300%', unit: '' },
      ],
    },
  ],
  // 实施路线图
  roadmap: [
    {
      phase: 'Phase 1',
      name: '基座构建',
      duration: 'Q1-Q2 2026',
      color: '#326ce5',
      icon: '🏗️',
      goals: [
        '统一数据接入层，覆盖 Top 20 核心数据源',
        '数据湖仓一体化（Iceberg + LakeFS）',
        '基础特征工程平台上线',
        'AI Coding 工具链标准化（Cursor + Claude + CI/CD）',
      ],
      deliverables: ['数据平台 v1.0', '特征仓库 v1.0', 'AI 开发规范 v1.0'],
      risk: '数据源接入的兼容性和稳定性',
    },
    {
      phase: 'Phase 2',
      name: '本体建模',
      duration: 'Q3-Q4 2026',
      color: '#6c5ce7',
      icon: '🧬',
      goals: [
        '核心业务领域 Ontology 建模（3-5 个关键领域）',
        '业务规则引擎上线，覆盖 Top 100 业务规则',
        '语义搜索 + RAG 系统上线',
        '数字孪生 PoC（选择 1 个业务场景）',
      ],
      deliverables: ['Ontology 平台 v1.0', '规则引擎 v1.0', 'RAG 系统 v1.0'],
      risk: '领域知识获取和建模的准确性',
    },
    {
      phase: 'Phase 3',
      name: 'AI 平台化',
      duration: 'Q1-Q2 2027',
      color: '#e17055',
      icon: '⚡',
      goals: [
        'Multi-Agent 编排框架上线',
        'Tool & API Gateway 统一管理',
        '安全护栏体系完善（多层校验 + 审计）',
        '首批 3-5 个 AI Agent 投入生产',
      ],
      deliverables: ['AI Platform v1.0', 'Agent Store v1.0', '安全护栏 v1.0'],
      risk: 'Agent 可靠性和安全性',
    },
    {
      phase: 'Phase 4',
      name: '决策引擎',
      duration: 'Q3-Q4 2027',
      color: '#3fb950',
      icon: '🎯',
      goals: [
        'AI Copilot 嵌入核心业务流程',
        '决策仪表盘覆盖关键业务指标',
        '自动化工作流覆盖率 > 50%',
        '数据飞轮闭环验证（用户反馈 → 模型优化 → 效果提升）',
      ],
      deliverables: ['AI Copilot v1.0', '决策中心 v1.0', '自动化引擎 v1.0'],
      risk: '业务用户接受度和变革管理',
    },
  ],
  // 团队能力转型
  teamTransformation: {
    before: [
      { role: '前端开发', count: '40%', icon: '🖥️' },
      { role: '后端开发', count: '35%', icon: '⚙️' },
      { role: '测试工程师', count: '15%', icon: '🧪' },
      { role: '产品经理', count: '10%', icon: '📋' },
    ],
    after: [
      { role: 'AI/ML 工程师', count: '25%', icon: '🤖', desc: 'Agent 开发 · 模型微调 · RAG · 评估' },
      { role: '平台工程师', count: '20%', icon: '☸️', desc: '数据平台 · AI Infra · DevOps · SRE' },
      { role: '领域工程师', count: '20%', icon: '🧬', desc: 'Ontology 建模 · 规则引擎 · 业务分析' },
      { role: '全栈开发', count: '15%', icon: '💻', desc: 'AI Copilot UI · 决策应用 · 可视化' },
      { role: '产品经理', count: '15%', icon: '🎯', desc: 'AI 产品设计 · 用户研究 · 商业化' },
      { role: '安全工程师', count: '5%', icon: '🔒', desc: 'AI 安全 · 合规 · 隐私 · 审计' },
    ],
  },
  // 关键成功指标
  kpis: [
    { category: '平台能力', metrics: [
      { name: '数据源覆盖率', target: '>80%', current: '~30%', icon: '📊' },
      { name: 'AI Agent 生产数量', target: '>20', current: '0', icon: '🤖' },
      { name: 'Ontology 实体覆盖', target: '>200 类', current: '0', icon: '🧬' },
      { name: '自动化率', target: '>70%', current: '~20%', icon: '⚙️' },
    ]},
    { category: '业务价值', metrics: [
      { name: '决策效率提升', target: '5-10x', current: '1x', icon: '⚡' },
      { name: '人工干预率', target: '<10%', current: '~80%', icon: '👤' },
      { name: '业务 ROI', target: '>300%', current: '~100%', icon: '💰' },
      { name: '客户 NRR', target: '>115%', current: '~100%', icon: '📈' },
    ]},
    { category: '团队能力', metrics: [
      { name: 'AI 工程师占比', target: '>25%', current: '~5%', icon: '🧑‍💻' },
      { name: 'AI 辅助代码占比', target: '>60%', current: '~20%', icon: '🤖' },
      { name: '领域知识沉淀', target: '>500 规则', current: '~50', icon: '📚' },
      { name: '人均产出提升', target: '3-5x', current: '1x', icon: '🚀' },
    ]},
  ],
};

// 5. 内部 SaaS 共用困境与交付形态
export const SAAS_DELIVERY = {
  title: '内部 SaaS 共用困境与交付形态',
  subtitle: '多部门共用一个大 SaaS 好不好？爆炸半径、交付形态到底怎么做？',

  // 大一统 SaaS 的核心困境
  sharedPlatformProblems: {
    title: '大一统 SaaS 平台的六大困境',
    desc: '公司内部做一个大 SaaS 让所有部门共用，看似降本增效，实则暗藏系统性风险',
    problems: [
      {
        id: 'blast_radius',
        name: '爆炸半径失控',
        icon: '💥',
        color: '#e17055',
        severity: '🔴 致命',
        desc: '一个部门的变更或故障，波及所有使用方。平台越大，爆炸半径越大，一次事故可能导致全公司业务瘫痪。',
        cases: [
          '某次数据库 Schema 变更导致 12 个业务线同时报错，恢复耗时 6 小时',
          '一个部门的流量突增触发限流，其他部门的正常请求被误杀',
          '安全漏洞修复需要所有业务线同时升级，协调成本远超修复成本',
          '一个低优先级功能的 Bug 导致核心交易链路降级',
        ],
        metrics: [
          { label: '平均故障影响范围', value: '5-12', unit: '个业务线' },
          { label: '变更协调周期', value: '2-4', unit: '周' },
          { label: '回滚复杂度', value: '指数级', unit: '' },
        ],
      },
      {
        id: 'requirement_conflict',
        name: '需求冲突与优先级博弈',
        icon: '⚔️',
        color: '#6c5ce7',
        severity: '🔴 致命',
        desc: '不同部门的需求方向、优先级、时间线完全不同，共用平台团队成为"需求漏斗"的瓶颈。',
        cases: [
          'A 部门要求高并发低延迟，B 部门要求强一致性，架构设计互相矛盾',
          '平台团队 80% 时间在协调需求优先级，20% 时间写代码',
          '小部门的紧急需求永远排在大部门后面，被迫自建"影子系统"',
          '版本发布节奏被最慢的业务线拖累，快速迭代的团队被迫等待',
        ],
        metrics: [
          { label: '需求排队周期', value: '4-8', unit: '周' },
          { label: '需求满足率', value: '<40%', unit: '' },
          { label: '影子系统数量', value: '持续增长', unit: '' },
        ],
      },
      {
        id: 'iteration_speed',
        name: '迭代速度塌陷',
        icon: '🐌',
        color: '#ffa657',
        severity: '🟡 严重',
        desc: '平台越大，每次变更的测试范围越广、回归成本越高、发布流程越长。创新速度被系统复杂度拖死。',
        cases: [
          '一个简单功能从需求到上线需要 6-8 周（需求评审→排期→开发→全量回归→灰度→全量）',
          '回归测试覆盖 200+ 场景，每次发布需要 3 天测试周期',
          '灰度发布需要所有业务线确认，一个部门不同意就无法推进',
          '技术债务累积导致每次迭代的边际成本递增',
        ],
        metrics: [
          { label: '发布周期', value: '2-4', unit: '周/次' },
          { label: '回归测试时间', value: '3-5', unit: '天' },
          { label: '年迭代次数', value: '<20', unit: '次' },
        ],
      },
      {
        id: 'org_coupling',
        name: '组织耦合',
        icon: '🔗',
        color: '#fd79a8',
        severity: '🟡 严重',
        desc: '康威定律的反面——共用平台迫使不同业务线在组织上深度耦合，决策链路过长，责任边界模糊。',
        cases: [
          '平台团队成为所有业务线的"公共依赖"，任何决策都需要多方会议',
          '出了问题互相甩锅：业务方说"平台不稳定"，平台方说"业务方用法不对"',
          '平台团队 KPI 与业务团队 KPI 冲突（稳定性 vs 快速上线）',
          '人员流动导致领域知识丢失，新人无法理解跨业务线的复杂逻辑',
        ],
        metrics: [
          { label: '跨团队会议', value: '5-10', unit: '次/周' },
          { label: '决策周期', value: '2-3x', unit: '倍' },
          { label: '责任归属争议', value: '频繁', unit: '' },
        ],
      },
      {
        id: 'customization_tax',
        name: '定制化税',
        icon: '🏷️',
        color: '#00cec9',
        severity: '🟡 严重',
        desc: '为满足不同部门的差异化需求，平台被迫引入大量配置项、开关、插件机制，系统复杂度指数级增长。',
        cases: [
          '配置项从最初的 20 个膨胀到 500+，没人能完全理解所有配置的交互效果',
          '为 A 部门加的"特殊逻辑"成为 B 部门的 Bug 来源',
          '插件机制设计不当，第三方插件导致主系统崩溃',
          '"万能平台"最终变成"万能屎山"，重构成本远超重建成本',
        ],
        metrics: [
          { label: '配置项数量', value: '500+', unit: '个' },
          { label: '条件分支', value: '指数增长', unit: '' },
          { label: '代码可读性', value: '持续下降', unit: '' },
        ],
      },
      {
        id: 'innovation_ceiling',
        name: '创新天花板',
        icon: '🚧',
        color: '#636e72',
        severity: '🟡 严重',
        desc: '平台必须向后兼容所有使用方，无法大胆采用新技术或新架构。技术选型被最保守的业务线锁定。',
        cases: [
          '想升级到新框架，但 3 个业务线还在用旧 API，迁移遥遥无期',
          '新技术 PoC 效果很好，但"全量推广影响面太大"被否决',
          '竞争对手已经用上新架构，我们还在维护 5 年前的技术栈',
          '优秀工程师因为"只能做维护，没有创新空间"而离职',
        ],
        metrics: [
          { label: '技术栈年龄', value: '3-5', unit: '年' },
          { label: '新技术采纳周期', value: '12-18', unit: '月' },
          { label: '工程师满意度', value: '偏低', unit: '' },
        ],
      },
    ],
  },

  // 爆炸半径深度分析
  blastRadiusAnalysis: {
    title: '爆炸半径深度分析',
    desc: '理解故障传播路径，才能设计有效的隔离策略',
    dimensions: [
      {
        name: '故障传播维度',
        icon: '🔥',
        color: '#e17055',
        layers: [
          { name: '基础设施层', desc: '数据库/缓存/消息队列故障 → 所有依赖方受影响', risk: '🔴 极高', isolation: '物理隔离 / 多集群' },
          { name: '服务层', desc: '核心服务异常 → 级联故障 → 雪崩效应', risk: '🔴 极高', isolation: '熔断 / 限流 / 降级' },
          { name: '数据层', desc: '数据污染/Schema 变更 → 下游数据错误 → 业务决策失误', risk: '🟡 高', isolation: '数据版本化 / 多租户隔离' },
          { name: '配置层', desc: '配置错误 → 行为异常 → 难以定位', risk: '🟡 高', isolation: '配置灰度 / 回滚机制' },
          { name: '业务逻辑层', desc: '规则冲突 → A 部门的正确是 B 部门的 Bug', risk: '🟡 中', isolation: '领域隔离 / 规则引擎' },
        ],
      },
      {
        name: '变更风险维度',
        icon: '🔄',
        color: '#6c5ce7',
        layers: [
          { name: 'API 变更', desc: '接口修改影响所有调用方，版本管理复杂', risk: '🔴 极高', isolation: 'API 版本化 / 契约测试' },
          { name: '数据模型变更', desc: 'Schema 演进需要所有消费方同步适配', risk: '🔴 极高', isolation: 'Schema Registry / 向后兼容' },
          { name: '依赖升级', desc: '底层库升级可能破坏上层业务逻辑', risk: '🟡 高', isolation: '依赖隔离 / 渐进式升级' },
          { name: '性能变更', desc: '优化 A 场景可能劣化 B 场景', risk: '🟡 中', isolation: '性能基线 / A/B 测试' },
        ],
      },
      {
        name: '组织传播维度',
        icon: '👥',
        color: '#3fb950',
        layers: [
          { name: '知识依赖', desc: '关键人员离职 → 领域知识断裂 → 系统不可维护', risk: '🔴 极高', isolation: '文档化 / 知识图谱 / Pair Programming' },
          { name: '流程耦合', desc: '发布/审批/测试流程互相阻塞', risk: '🟡 高', isolation: '独立发布流水线 / 自动化测试' },
          { name: '沟通成本', desc: '跨团队协调的时间成本随团队数量平方级增长', risk: '🟡 高', isolation: '明确接口契约 / 异步沟通' },
        ],
      },
    ],
  },

  // 软件交付形态演进
  deliveryEvolution: {
    title: '软件交付形态演进',
    desc: '从大一统到领域自治的演进路径',
    stages: [
      {
        id: 'monolith',
        name: '大一统平台',
        subtitle: 'Monolithic Shared Platform',
        icon: '🏢',
        color: '#636e72',
        era: '2010-2018',
        desc: '一个平台服务所有部门，统一技术栈、统一数据库、统一发布',
        pros: ['初期开发效率高', '技术栈统一易管理', '数据天然互通', '人力集中投入'],
        cons: ['爆炸半径大', '迭代速度慢', '需求冲突严重', '创新受限'],
        blastRadius: '🔴 全公司',
        autonomy: '⭐',
        scalability: '⭐⭐',
        bestFor: '初创期 / 业务线 < 3 / 团队 < 30 人',
      },
      {
        id: 'microservice',
        name: '微服务化',
        subtitle: 'Microservices Architecture',
        icon: '🧩',
        color: '#326ce5',
        era: '2015-2022',
        desc: '按技术能力拆分为独立服务，各服务独立部署、独立扩展',
        pros: ['服务级别隔离', '独立部署', '技术栈灵活', '团队自治'],
        cons: ['分布式复杂度', '数据一致性难题', '运维成本高', '服务间调用链长'],
        blastRadius: '🟡 单服务 + 下游',
        autonomy: '⭐⭐⭐',
        scalability: '⭐⭐⭐⭐',
        bestFor: '中等规模 / 技术团队成熟 / 有 DevOps 基础',
      },
      {
        id: 'domain_platform',
        name: '领域平台',
        subtitle: 'Domain-Oriented Platform',
        icon: '🏗️',
        color: '#6c5ce7',
        era: '2020-2025',
        desc: '按业务领域划分平台边界，每个领域平台独立演进，通过标准化接口互通',
        pros: ['领域自治', '爆炸半径可控', '业务语义清晰', '独立演进节奏'],
        cons: ['领域边界划分难', '跨域协调成本', '重复建设风险', '需要强治理'],
        blastRadius: '🟢 单领域',
        autonomy: '⭐⭐⭐⭐',
        scalability: '⭐⭐⭐⭐',
        bestFor: '大型组织 / 多业务线 / 领域边界清晰',
      },
      {
        id: 'embedded_capability',
        name: '嵌入式能力',
        subtitle: 'Embedded AI-Native Capability',
        icon: '🧬',
        color: '#3fb950',
        era: '2025+',
        desc: '不再是"共用平台"，而是将核心能力（数据/AI/安全）以 SDK/Agent/API 形式嵌入各业务线，业务线拥有完全自主权',
        pros: ['零爆炸半径', '完全自治', 'AI 原生', '按需组合', '极速迭代'],
        cons: ['能力一致性挑战', '版本碎片化', '需要强标准', '治理复杂度转移'],
        blastRadius: '🟢 单业务线',
        autonomy: '⭐⭐⭐⭐⭐',
        scalability: '⭐⭐⭐⭐⭐',
        bestFor: 'AI 时代 / 业务线高度自治 / 有平台工程能力',
      },
    ],
  },

  // 最佳实践：交付形态决策框架
  deliveryFramework: {
    title: '交付形态决策框架',
    subtitle: '没有银弹，只有适合的选择',
    principles: [
      {
        name: '爆炸半径最小化原则',
        icon: '🛡️',
        color: '#e17055',
        desc: '任何单点故障的影响范围必须可控。设计时先画"爆炸半径图"，再决定架构边界。',
        practices: [
          '故障域隔离：不同业务线的数据、计算、网络物理隔离',
          '变更灰度：任何变更先在最小范围验证，逐步扩大',
          '熔断降级：下游故障时自动降级，不传播到上游',
          '混沌工程：定期注入故障，验证隔离机制有效性',
        ],
      },
      {
        name: '领域自治原则',
        icon: '🏛️',
        color: '#6c5ce7',
        desc: '每个业务领域拥有自己的数据、服务和发布节奏。跨域通过契约而非共享数据库交互。',
        practices: [
          '领域驱动设计（DDD）：明确限界上下文和领域边界',
          '数据所有权：每个领域拥有自己的数据存储，禁止跨域直接读写',
          '契约优先：API 契约先于实现，变更需要消费方确认',
          '独立发布：每个领域可以独立发布，不需要全局协调',
        ],
      },
      {
        name: '能力下沉原则',
        icon: '⬇️',
        color: '#3fb950',
        desc: '通用能力（认证/监控/日志/AI）以 SDK/Sidecar 形式下沉到业务线，而非集中式平台。',
        practices: [
          'SDK 化：核心能力封装为版本化 SDK，业务线按需引入',
          'Sidecar 模式：基础设施能力通过 Sidecar 代理注入，对业务透明',
          'Platform as a Product：平台团队像产品团队一样运营，SDK 是产品',
          '版本兼容：SDK 严格遵循语义化版本，向后兼容至少 2 个大版本',
        ],
      },
      {
        name: 'AI Agent 原生原则',
        icon: '🤖',
        color: '#ffa657',
        desc: 'AI 时代的交付形态应该是 Agent 原生的——能力以 Agent 可调用的工具/API 形式存在。',
        practices: [
          'MCP/Tool 化：所有平台能力注册为 AI Agent 可调用的工具',
          '自描述 API：API 自带语义描述，Agent 无需人工编排即可理解和调用',
          '意图驱动：业务方表达意图（"我要分析用户留存"），Agent 自动编排底层能力',
          '反馈闭环：Agent 调用结果自动反馈，持续优化工具质量',
        ],
      },
    ],
    // 决策矩阵
    decisionMatrix: [
      { dimension: '团队规模', monolith: '< 30 人 ✅', microservice: '30-200 人 ✅', domain: '200-1000 人 ✅', embedded: '> 200 人 ✅' },
      { dimension: '业务线数量', monolith: '1-3 ✅', microservice: '3-10 ✅', domain: '5-20 ✅', embedded: '> 10 ✅' },
      { dimension: '迭代速度要求', monolith: '月级 ✅', microservice: '周级 ✅', domain: '周级 ✅', embedded: '天级 ✅' },
      { dimension: '爆炸半径容忍度', monolith: '高（可接受全局影响）', microservice: '中（服务级隔离）', domain: '低（领域级隔离）', embedded: '极低（业务线级隔离）' },
      { dimension: '技术团队成熟度', monolith: '初级 ✅', microservice: '中级 ✅', domain: '高级 ✅', embedded: '高级 ✅' },
      { dimension: 'AI 能力需求', monolith: '低', microservice: '中', domain: '中-高', embedded: '高（AI 原生）' },
      { dimension: '运维复杂度', monolith: '⭐', microservice: '⭐⭐⭐⭐', domain: '⭐⭐⭐', embedded: '⭐⭐⭐' },
      { dimension: '初始建设成本', monolith: '⭐', microservice: '⭐⭐⭐', domain: '⭐⭐⭐⭐', embedded: '⭐⭐⭐⭐' },
    ],
    // 推荐路径
    recommendedPath: {
      title: '推荐演进路径',
      desc: '不要一步到位，渐进式演进才是正道',
      steps: [
        {
          phase: 'Phase 1',
          name: '识别爆炸半径',
          duration: '1-2 月',
          icon: '🔍',
          color: '#e17055',
          actions: [
            '梳理当前平台的所有使用方和依赖关系',
            '绘制故障传播图，标记高风险路径',
            '统计过去 12 个月的故障影响范围数据',
            '识别"必须隔离"的核心业务线',
          ],
        },
        {
          phase: 'Phase 2',
          name: '领域边界划分',
          duration: '2-3 月',
          icon: '✂️',
          color: '#6c5ce7',
          actions: [
            '用 DDD 方法识别限界上下文',
            '按业务领域（而非技术层）划分平台边界',
            '定义领域间的接口契约和数据所有权',
            '选择 1-2 个领域做试点拆分',
          ],
        },
        {
          phase: 'Phase 3',
          name: '能力 SDK 化',
          duration: '3-6 月',
          icon: '📦',
          color: '#3fb950',
          actions: [
            '将通用能力（认证/监控/日志）封装为 SDK',
            '建立 SDK 版本管理和兼容性策略',
            '试点业务线从"调用平台 API"迁移到"引入 SDK"',
            '建立 Platform as a Product 的运营机制',
          ],
        },
        {
          phase: 'Phase 4',
          name: 'Agent 原生化',
          duration: '6-12 月',
          icon: '🤖',
          color: '#ffa657',
          actions: [
            '所有平台能力注册为 MCP Tool',
            '构建 AI Agent 编排层，支持意图驱动调用',
            '业务线通过 Agent 而非直接 API 使用平台能力',
            '建立反馈闭环，持续优化工具质量和 Agent 效果',
          ],
        },
      ],
    },
  },

  // 真实案例与教训
  realWorldLessons: {
    title: '真实案例与教训',
    cases: [
      {
        name: '某大厂统一中台翻车',
        icon: '🏢',
        color: '#e17055',
        scenario: '2019 年某互联网大厂推行"大中台"战略，将所有业务线的通用能力收归中台团队统一建设。',
        problems: [
          '中台团队成为全公司瓶颈，需求排队 3-6 个月',
          '一次中台升级导致 8 个业务线同时故障，损失数千万',
          '业务线为绕过中台，私建"影子系统"，数据孤岛反而更多',
          '中台团队 KPI 是"平台稳定性"，业务团队 KPI 是"快速上线"，根本性冲突',
        ],
        lesson: '中台不是万能药。当中台成为瓶颈时，它的存在反而降低了整体效率。正确做法是"能力下沉"而非"能力集中"。',
      },
      {
        name: 'Shopify 的 Modular Monolith',
        icon: '🛒',
        color: '#3fb950',
        scenario: 'Shopify 没有走微服务路线，而是选择了"模块化单体"——在单体应用内部划分清晰的模块边界，模块间通过接口通信。',
        problems: [
          '初期微服务化尝试导致运维复杂度爆炸',
          '分布式事务和数据一致性问题消耗大量工程资源',
          '服务间调用链过长，排查问题困难',
        ],
        lesson: '微服务不是唯一答案。Shopify 证明了"模块化单体"在特定规模下可以兼顾隔离性和简单性。关键是模块边界清晰，而非物理拆分。',
      },
      {
        name: 'Amazon 的 Two-Pizza Team',
        icon: '🍕',
        color: '#ffa657',
        scenario: 'Amazon 的"两个披萨团队"原则——每个团队足够小（6-10 人），拥有自己的服务、数据和发布流程，对外提供 API。',
        problems: [
          '初期大量重复建设，同一功能被多个团队独立实现',
          '跨团队协调依赖严格的 API 契约和文档',
          '需要强大的基础设施团队支撑（AWS 就是这么诞生的）',
        ],
        lesson: '小团队 + 明确所有权 + API 契约 = 最大化自治和创新速度。重复建设的成本远低于协调成本。AWS 本身就是"内部平台能力产品化"的最佳案例。',
      },
      {
        name: 'Palantir 的 Forward Deployed 模式',
        icon: '🏛️',
        color: '#6c5ce7',
        scenario: 'Palantir 不做"通用 SaaS"，而是派工程师驻场客户，基于通用平台（Foundry）为每个客户深度定制。',
        problems: [
          '人力成本高，扩展速度受限',
          '每个客户的定制化代码难以复用',
          '工程师驻场模式对人才要求极高',
        ],
        lesson: '通用平台 + 深度定制的组合模式。平台提供 80% 的通用能力，剩下 20% 由驻场工程师根据客户业务深度定制。这 20% 才是真正的价值和护城河。',
      },
    ],
  },
};

// 6. FDE × 业务 BP × 交付飞轮
export const FDE_BP_FLYWHEEL = {
  title: 'FDE × 业务 BP × 交付飞轮',
  subtitle: '从"远程交付"到"嵌入式共创"——Palantir FDE 模式的本土化演进',

  // FDE 与业务 BP 概念对比
  roleComparison: {
    title: '角色定义与对比',
    desc: '理解 FDE 和业务 BP 的本质区别，才能设计正确的交付模式',
    roles: [
      {
        id: 'fde',
        name: 'Forward Deployed Engineer (FDE)',
        origin: 'Palantir',
        icon: '🪖',
        color: '#6c5ce7',
        tagline: '技术军师，驻场作战',
        definition: '由平台方派出的高级工程师，驻场到客户/业务方 6-18 个月，深度理解业务后基于平台能力构建定制化解决方案。不是"外包"，而是"技术特种兵"。',
        keyTraits: [
          { trait: '技术深度', desc: '精通平台底层架构，能快速将平台能力适配到业务场景', level: '⭐⭐⭐⭐⭐' },
          { trait: '业务理解', desc: '驻场期间深度学习业务领域知识，成为"懂技术的业务专家"', level: '⭐⭐⭐⭐' },
          { trait: '交付能力', desc: '独立完成从需求分析到上线部署的全链路，不依赖后方团队', level: '⭐⭐⭐⭐⭐' },
          { trait: '知识回流', desc: '将业务场景中的通用需求抽象回平台，驱动平台进化', level: '⭐⭐⭐⭐⭐' },
        ],
        dayInLife: [
          '09:00 参加业务方晨会，了解当日业务重点和痛点',
          '10:00 与业务方 1:1 深挖某个决策流程的瓶颈',
          '11:00 基于平台 Ontology 建模业务实体和规则',
          '14:00 开发定制化 AI Agent / 决策仪表盘',
          '16:00 与平台团队同步，提交通用能力需求',
          '17:00 给业务方演示 Demo，收集反馈迭代',
        ],
        antiPatterns: [
          '❌ 不是外包——FDE 代表平台方利益，目标是让业务方深度绑定平台',
          '❌ 不是售前——FDE 真正写代码、做交付，不是画 PPT',
          '❌ 不是驻场运维——FDE 创造新价值，不是维护旧系统',
          '❌ 不是一次性项目——FDE 建立的是持续运转的系统，不是交付后就走',
        ],
      },
      {
        id: 'bp',
        name: 'Business Partner (业务 BP)',
        origin: '互联网大厂',
        icon: '🤝',
        color: '#3fb950',
        tagline: '业务翻译官，需求桥梁',
        definition: '由平台/中台团队派出的业务对接人，负责理解业务方需求并翻译为技术方案，协调平台团队排期交付。本质是"需求中转站"和"沟通桥梁"。',
        keyTraits: [
          { trait: '技术深度', desc: '了解平台能力边界，但通常不直接写代码', level: '⭐⭐⭐' },
          { trait: '业务理解', desc: '理解业务方的语言和需求，但深度有限', level: '⭐⭐⭐' },
          { trait: '交付能力', desc: '依赖后方平台团队排期开发，自身不直接交付', level: '⭐⭐' },
          { trait: '知识回流', desc: '传递需求信息，但抽象和沉淀能力有限', level: '⭐⭐' },
        ],
        dayInLife: [
          '09:00 收集业务方本周需求清单',
          '10:00 与平台产品经理对齐需求优先级',
          '11:00 编写需求文档，翻译业务语言为技术语言',
          '14:00 参加平台团队排期会，争取资源',
          '16:00 向业务方同步排期结果和预期交付时间',
          '17:00 跟进上周需求的开发进度',
        ],
        antiPatterns: [
          '⚠️ 容易变成"传话筒"——两头传话，两头不满意',
          '⚠️ 容易变成"需求漏斗"——收集了 100 个需求，平台只能做 10 个',
          '⚠️ 容易变成"背锅侠"——业务方怪排期慢，平台方怪需求不清',
          '⚠️ 容易变成"信息孤岛"——BP 离职后，业务知识随之丢失',
        ],
      },
    ],
    // 核心差异对比
    comparison: [
      { dimension: '核心定位', fde: '技术特种兵，独立作战', bp: '沟通桥梁，协调资源', winner: 'fde' },
      { dimension: '交付方式', fde: '自己写代码，直接交付', bp: '写需求文档，等后方排期', winner: 'fde' },
      { dimension: '业务深度', fde: '驻场 6-18 月，深度浸泡', bp: '定期对接，表层理解', winner: 'fde' },
      { dimension: '响应速度', fde: '当天需求当天响应', bp: '需求排队 4-8 周', winner: 'fde' },
      { dimension: '知识沉淀', fde: '抽象为平台能力 + Ontology', bp: '停留在需求文档层面', winner: 'fde' },
      { dimension: '可扩展性', fde: '人力密集，扩展受限', bp: '轻量级，易复制', winner: 'bp' },
      { dimension: '人才要求', fde: '全栈 + 业务理解，极稀缺', bp: '沟通能力为主，较易招聘', winner: 'bp' },
      { dimension: '成本', fde: '高（高级工程师驻场）', bp: '中（协调角色）', winner: 'bp' },
    ],
    // 进化方向：FDE + AI = 超级 BP
    evolution: {
      title: 'FDE + AI Agent = 超级业务 BP',
      desc: '用 AI Agent 替代 FDE 的重复性工作，让 FDE 聚焦高价值的业务理解和架构设计',
      icon: '🚀',
      color: '#e17055',
      stages: [
        { name: '传统 BP', desc: '需求传话筒，等排期', icon: '📋', efficiency: '1x', color: '#636e72' },
        { name: 'FDE 驻场', desc: '独立交付，深度绑定', icon: '🪖', efficiency: '5x', color: '#6c5ce7' },
        { name: 'FDE + AI Copilot', desc: 'AI 辅助编码，FDE 聚焦架构', icon: '🤖', efficiency: '10x', color: '#3fb950' },
        { name: 'AI Agent + FDE 督导', desc: 'Agent 自主交付，FDE 做质量把关和业务决策', icon: '🧠', efficiency: '20x', color: '#e17055' },
      ],
    },
  },

  // 交付飞轮模型
  deliveryFlywheel: {
    title: '交付飞轮模型',
    desc: 'FDE 驻场不是一次性项目，而是驱动平台持续进化的飞轮引擎',
    // 飞轮的四个阶段
    stages: [
      {
        id: 'embed',
        name: '嵌入',
        subtitle: 'Embed & Understand',
        icon: '🔍',
        color: '#6c5ce7',
        desc: 'FDE 驻场业务方，深度理解业务流程、决策逻辑、数据流向和痛点',
        inputs: ['业务方的领域知识', '真实业务流程和数据', '一线用户的痛点反馈'],
        outputs: ['业务领域 Ontology 模型', '关键决策流程图', '数据资产清单'],
        duration: '1-3 月',
        keyActions: [
          '跟随业务方日常工作，观察真实决策过程',
          '绘制业务实体关系图和决策流程图',
          '识别"AI 可以替代"和"必须人工判断"的环节',
          '建立业务方信任，成为"自己人"',
        ],
        metrics: [
          { label: '业务流程覆盖', value: '>80%' },
          { label: '关键决策点识别', value: '>20 个' },
          { label: '业务方信任度', value: '高' },
        ],
      },
      {
        id: 'deliver',
        name: '交付',
        subtitle: 'Build & Deliver',
        icon: '⚡',
        color: '#e17055',
        desc: '基于平台能力快速构建定制化解决方案，让业务方看到即时价值',
        inputs: ['业务 Ontology 模型', '平台核心能力（数据/AI/工具）', '业务方的优先级排序'],
        outputs: ['定制化 AI Agent / Copilot', '决策仪表盘', '自动化工作流', '业务方的"Aha Moment"'],
        duration: '2-6 月',
        keyActions: [
          '选择 1-2 个高价值场景快速交付 MVP',
          '基于平台 SDK/API 构建，而非从零开发',
          '每周 Demo，快速迭代，让业务方参与共创',
          '记录所有定制化需求，标记"可通用化"的部分',
        ],
        metrics: [
          { label: '首个 MVP 交付', value: '<4 周' },
          { label: '业务方满意度', value: '>4.5/5' },
          { label: '决策效率提升', value: '3-5x' },
        ],
      },
      {
        id: 'abstract',
        name: '抽象',
        subtitle: 'Abstract & Generalize',
        icon: '🧬',
        color: '#3fb950',
        desc: '将业务场景中的定制化方案抽象为平台通用能力，反哺平台进化',
        inputs: ['多个业务场景的定制化代码', '跨业务线的共性需求', 'FDE 的业务洞察'],
        outputs: ['新的平台 SDK 模块', '通用 Ontology 模板', '最佳实践 Playbook', '平台能力升级'],
        duration: '持续进行',
        keyActions: [
          '识别 3+ 个业务线都需要的共性能力',
          '将定制化代码重构为可配置的平台模块',
          '编写 Ontology 模板和最佳实践文档',
          '与平台团队协作，将模块合入平台主线',
        ],
        metrics: [
          { label: '通用化模块', value: '>5 个/季度' },
          { label: '代码复用率', value: '>60%' },
          { label: '平台能力增长', value: '持续' },
        ],
      },
      {
        id: 'scale',
        name: '规模化',
        subtitle: 'Scale & Replicate',
        icon: '🚀',
        color: '#ffa657',
        desc: '通用化的能力让下一个业务线的接入更快、成本更低，飞轮加速转动',
        inputs: ['平台通用能力库', 'Ontology 模板库', '最佳实践 Playbook'],
        outputs: ['新业务线快速接入', 'FDE 效率倍增', '平台 NRR 提升', '数据飞轮启动'],
        duration: '持续加速',
        keyActions: [
          '新业务线接入时间从 6 月缩短到 2 月',
          'FDE 从"从零建设"变为"模板化部署 + 定制化调优"',
          '业务方自助使用平台能力的比例持续提升',
          '数据越多 → AI 越准 → 业务越依赖 → 更多数据',
        ],
        metrics: [
          { label: '新业务接入周期', value: '<2 月' },
          { label: 'FDE 人效', value: '3x 提升' },
          { label: '业务自助率', value: '>50%' },
        ],
      },
    ],
    // 飞轮加速器
    accelerators: [
      {
        name: 'AI Agent 替代重复工作',
        icon: '🤖',
        color: '#6c5ce7',
        desc: 'FDE 在第一个业务线手动做的事，AI Agent 在后续业务线自动做',
        examples: [
          '数据接入：FDE 手动写 ETL → Agent 自动生成数据管道',
          'Ontology 建模：FDE 手动建模 → Agent 基于数据自动推荐实体关系',
          '仪表盘搭建：FDE 手动配置 → Agent 根据业务目标自动生成',
          '异常检测规则：FDE 手动编写 → Agent 从历史数据中自动学习',
        ],
      },
      {
        name: 'Ontology 模板复用',
        icon: '🧬',
        color: '#3fb950',
        desc: '同行业/同类型业务线的 Ontology 高度相似，模板化后可快速复用',
        examples: [
          '电商 Ontology：用户/商品/订单/支付/物流 → 90% 可复用',
          '金融 Ontology：账户/交易/风控/合规 → 85% 可复用',
          '制造 Ontology：设备/产线/工单/质检 → 80% 可复用',
          '自动驾驶 Ontology：场景/传感器/标注/模型 → 75% 可复用',
        ],
      },
      {
        name: 'Playbook 标准化',
        icon: '📖',
        color: '#e17055',
        desc: '将 FDE 的驻场经验编码为可执行的 Playbook，新 FDE 可快速上手',
        examples: [
          'Week 1 Playbook：业务方关系建立 + 核心流程梳理',
          'Week 2-4 Playbook：数据资产盘点 + Ontology 初版',
          'Month 2-3 Playbook：MVP 交付 + 快速迭代',
          'Month 4-6 Playbook：能力抽象 + 平台回流',
        ],
      },
      {
        name: '数据飞轮效应',
        icon: '🔄',
        color: '#ffa657',
        desc: '每个业务线接入后，平台数据量增加 → AI 模型更准 → 吸引更多业务线',
        examples: [
          '业务线 A 的数据训练出的异常检测模型，在业务线 B 直接可用',
          '跨业务线的用户行为数据，让推荐算法效果提升 30%',
          '多业务线的运营数据，让预测模型的泛化能力显著增强',
          '数据量每翻一倍，AI 准确率提升 5-10%',
        ],
      },
    ],
    // 飞轮效果量化
    flywheelMetrics: {
      title: '飞轮效果量化',
      rounds: [
        { round: '第 1 轮', bizLines: '1-2', fdeCount: '2-3', deliveryCycle: '6 月', platformModules: '5', reuse: '0%', desc: '从零建设，全部定制化' },
        { round: '第 2 轮', bizLines: '3-5', fdeCount: '3-5', deliveryCycle: '3 月', platformModules: '15', reuse: '40%', desc: '模板复用开始生效' },
        { round: '第 3 轮', bizLines: '5-10', fdeCount: '5-8', deliveryCycle: '6 周', platformModules: '30', reuse: '60%', desc: 'AI Agent 开始替代重复工作' },
        { round: '第 4 轮', bizLines: '10-20', fdeCount: '8-12', deliveryCycle: '2 周', platformModules: '50+', reuse: '80%', desc: '业务方可自助接入，FDE 聚焦高价值场景' },
      ],
    },
  },

  // FDE 团队建设
  fdeTeamBuilding: {
    title: 'FDE 团队建设',
    desc: '如何在公司内部建立 FDE 能力',
    talentProfile: {
      title: 'FDE 人才画像',
      must: [
        { trait: '全栈工程能力', desc: '前后端 + 数据 + AI，能独立完成端到端交付', icon: '💻' },
        { trait: '快速学习能力', desc: '2-4 周内理解一个新业务领域的核心逻辑', icon: '🧠' },
        { trait: '沟通与共情', desc: '能用业务方的语言沟通，理解他们的真实痛点', icon: '🗣️' },
        { trait: '抽象思维', desc: '从具体场景中提炼通用模式，驱动平台进化', icon: '🔬' },
      ],
      nice: [
        { trait: '行业经验', desc: '有目标行业的从业经验，缩短业务理解周期', icon: '🏭' },
        { trait: 'AI/ML 能力', desc: '能训练和部署模型，构建 AI Agent', icon: '🤖' },
        { trait: '产品思维', desc: '不只是完成需求，而是思考"什么才是正确的需求"', icon: '🎯' },
      ],
    },
    careerPath: {
      title: 'FDE 职业发展路径',
      levels: [
        { level: 'FDE I', duration: '0-2 年', desc: '跟随资深 FDE 驻场，学习业务理解和快速交付', focus: '执行力 + 技术深度', color: '#79c0ff' },
        { level: 'FDE II', duration: '2-4 年', desc: '独立负责 1 个业务线的驻场交付，开始抽象通用能力', focus: '独立交付 + 知识回流', color: '#6c5ce7' },
        { level: 'Senior FDE', duration: '4-6 年', desc: '同时负责 2-3 个业务线，指导 FDE I/II，驱动平台进化', focus: '架构设计 + 团队培养', color: '#e17055' },
        { level: 'FDE Lead', duration: '6+ 年', desc: '负责整个 FDE 团队的战略规划、人才培养和飞轮运转', focus: '战略规划 + 组织建设', color: '#3fb950' },
      ],
    },
    operatingModel: {
      title: 'FDE 运营模式',
      principles: [
        {
          name: '轮岗制',
          icon: '🔄',
          desc: 'FDE 每 6-12 个月轮换业务线，避免"被业务方绑架"，同时积累跨领域经验',
        },
        {
          name: '双线汇报',
          icon: '📊',
          desc: 'FDE 向平台团队和业务方双线汇报。平台团队考核"能力回流"，业务方考核"交付价值"',
        },
        {
          name: '知识共享会',
          icon: '📢',
          desc: '每月 FDE 团队内部分享会，交流不同业务线的经验和通用化机会',
        },
        {
          name: 'AI 工具赋能',
          icon: '🤖',
          desc: '为 FDE 配备最强 AI 工具链（Cursor + Claude + MCP），让 FDE 的人效最大化',
        },
      ],
    },
  },
};

// 7. 外部模型接触内部数据的风险与可控性方案
export const EXTERNAL_MODEL_SECURITY = {
  title: '外部模型接触内部数据的风险与可控性方案',
  subtitle: '类 Claude 等外部大模型接触公司内部代码和数据的安全论证',

  // 核心问题定义
  coreProblem: {
    title: '核心问题',
    desc: '当团队使用 Claude / GPT-4 / Gemini 等外部大模型辅助编码和数据分析时，公司内部代码、业务数据、架构设计等敏感信息不可避免地被发送到第三方服务器。这带来了哪些风险？如何在"效率提升"和"安全合规"之间找到平衡？',
    stakeholders: [
      { role: '工程团队', concern: '效率提升 vs 代码泄露', icon: '👨‍💻' },
      { role: '安全团队', concern: '数据保护 vs 工具可用性', icon: '🔒' },
      { role: '法务合规', concern: '合同条款 vs 监管要求', icon: '⚖️' },
      { role: '管理层', concern: '竞争力 vs 风险敞口', icon: '📊' },
    ],
    verdict: {
      summary: '不用外部模型的风险 > 用外部模型的风险',
      explanation: '在 AI Coding 时代，不使用外部模型意味着团队效率落后竞争对手 3-5x，人才流失加速。关键不是"用不用"，而是"怎么用"——建立分级管控体系，让风险可控、可审计、可追溯。',
    },
  },

  // 风险全景图
  riskLandscape: {
    title: '风险全景图',
    desc: '系统性梳理外部模型接触内部数据的六大风险维度',
    risks: [
      {
        id: 'data_leakage',
        name: '数据泄露风险',
        icon: '🔓',
        color: '#e17055',
        severity: '🔴 高',
        desc: '发送给外部模型的代码和数据可能被模型提供商存储、用于训练、或因安全漏洞泄露给第三方。',
        scenarios: [
          '工程师将包含数据库密码、API Key 的配置文件发送给 Claude 调试',
          '将核心算法/交易策略代码粘贴到外部模型进行优化',
          '将用户 PII（个人身份信息）数据发送给模型进行分析',
          '将内部架构设计文档发送给模型生成技术方案',
        ],
        realCases: [
          { date: '2023-04', event: 'Samsung 工程师将芯片源代码粘贴到 ChatGPT，导致核心 IP 泄露', impact: '全面禁用 ChatGPT，后改为内部部署方案' },
          { date: '2024-01', event: '某金融公司员工将客户交易数据发送给 GPT-4 做分析，违反 GDPR', impact: '被监管机构罚款 €2M，CTO 引咎辞职' },
          { date: '2024-06', event: 'OpenAI 内部安全事件，部分企业 API 调用日志短暂暴露', impact: '多家企业紧急审查 API 调用历史' },
          { date: '2025-03', event: '某科技公司发现员工通过 Cursor 将整个代码仓库索引发送到 Claude API', impact: '紧急部署代码扫描网关' },
        ],
        mitigations: [
          { name: 'API 模式 + 零留存协议', desc: '使用 API 而非 Web 界面，签署数据零留存（Zero Data Retention）协议', effectiveness: '⭐⭐⭐⭐' },
          { name: '敏感信息过滤网关', desc: '在请求发送前自动检测并脱敏 API Key、密码、PII 等敏感信息', effectiveness: '⭐⭐⭐⭐⭐' },
          { name: '代码分级管控', desc: '按代码敏感度分级（公开/内部/机密/绝密），不同级别不同策略', effectiveness: '⭐⭐⭐⭐' },
          { name: '审计日志', desc: '记录所有发送给外部模型的内容，支持事后审计和追溯', effectiveness: '⭐⭐⭐⭐' },
        ],
      },
      {
        id: 'ip_risk',
        name: '知识产权风险',
        icon: '©️',
        color: '#6c5ce7',
        severity: '🔴 高',
        desc: '核心代码和算法发送给外部模型后，可能丧失商业秘密保护资格；模型生成的代码可能存在版权争议。',
        scenarios: [
          '核心推荐算法代码被发送给外部模型，可能不再满足"商业秘密"的保密性要件',
          '模型生成的代码可能包含开源代码片段，引入 GPL 等传染性许可证风险',
          '竞争对手使用同一模型，可能获得相似的技术方案',
          '专利申请中的技术方案被发送给模型，可能影响新颖性',
        ],
        realCases: [
          { date: '2024-03', event: 'GitHub Copilot 集体诉讼：开发者指控 Copilot 生成的代码直接复制开源项目', impact: '案件仍在审理，但已引发行业对 AI 生成代码版权的广泛讨论' },
          { date: '2024-09', event: '美国版权局裁定：纯 AI 生成的代码不受版权保护', impact: '企业需要证明"人类创造性贡献"才能获得版权' },
          { date: '2025-01', event: '某公司因将专利申请中的算法发送给 ChatGPT，被专利审查员质疑新颖性', impact: '专利申请被驳回，损失数百万研发投入' },
        ],
        mitigations: [
          { name: '核心 IP 隔离', desc: '核心算法、交易策略、专利技术禁止发送给外部模型', effectiveness: '⭐⭐⭐⭐⭐' },
          { name: '开源合规扫描', desc: '对模型生成的代码进行开源许可证扫描（如 FOSSA / Snyk）', effectiveness: '⭐⭐⭐⭐' },
          { name: '版权声明策略', desc: '在 AI 辅助代码中标注人类贡献部分，确保版权可主张', effectiveness: '⭐⭐⭐' },
          { name: '竞业隔离', desc: '与模型提供商签署竞业条款，禁止将数据用于竞品训练', effectiveness: '⭐⭐⭐⭐' },
        ],
      },
      {
        id: 'compliance_risk',
        name: '合规监管风险',
        icon: '⚖️',
        color: '#fd79a8',
        severity: '🔴 高',
        desc: '跨境数据传输、行业监管要求、数据保护法规等合规风险。不同行业和地区的监管要求差异巨大。',
        scenarios: [
          '中国公司使用美国 Claude API，涉及数据出境安全评估',
          '金融行业数据发送给外部模型，违反银保监会数据治理要求',
          '医疗数据发送给外部模型，违反 HIPAA / 医疗数据安全管理办法',
          '欧洲业务数据发送给美国模型，违反 GDPR 跨境传输规定',
        ],
        realCases: [
          { date: '2023-06', event: '意大利数据保护局暂时禁止 ChatGPT，理由是违反 GDPR', impact: 'OpenAI 紧急增加欧洲数据处理选项和隐私控制' },
          { date: '2024-08', event: '中国网信办发布《生成式人工智能服务管理暂行办法》', impact: '要求境内服务使用合法数据训练，跨境数据需安全评估' },
          { date: '2025-02', event: '某银行因使用外部 AI 分析客户数据被银保监会约谈', impact: '全行暂停外部 AI 工具使用，启动合规整改' },
        ],
        mitigations: [
          { name: '数据出境评估', desc: '按《数据出境安全评估办法》完成评估，或使用境内部署的模型', effectiveness: '⭐⭐⭐⭐⭐' },
          { name: '行业合规映射', desc: '建立行业监管要求与 AI 使用策略的映射表，按行业定制管控', effectiveness: '⭐⭐⭐⭐' },
          { name: '合规审计链', desc: '完整记录数据流向、处理目的、法律依据，支持监管审查', effectiveness: '⭐⭐⭐⭐' },
          { name: '境内模型备选', desc: '为高合规要求场景准备境内部署的模型（DeepSeek / Qwen / GLM）', effectiveness: '⭐⭐⭐⭐⭐' },
        ],
      },
      {
        id: 'supply_chain_risk',
        name: '供应链依赖风险',
        icon: '🔗',
        color: '#ffa657',
        severity: '🟡 中',
        desc: '过度依赖单一外部模型提供商，面临服务中断、价格上涨、政策变化等供应链风险。',
        scenarios: [
          'Anthropic 突然调整 API 价格，成本翻倍',
          '模型提供商因政策原因停止对某些地区的服务',
          'API 服务中断导致开发流程停滞',
          '模型版本更新导致生成质量波动，影响开发效率',
        ],
        realCases: [
          { date: '2024-03', event: 'OpenAI 对中国区 API 访问施加限制', impact: '大量中国开发者被迫迁移到其他模型' },
          { date: '2024-11', event: 'Anthropic Claude API 价格调整，部分企业成本增加 40%', impact: '企业开始评估多模型策略' },
          { date: '2025-01', event: '某公司核心开发流程深度绑定 Cursor + Claude，Claude API 故障 4 小时导致全员停工', impact: '紧急建立多模型 Fallback 机制' },
        ],
        mitigations: [
          { name: '多模型策略', desc: '同时接入 Claude / GPT / Gemini / DeepSeek，避免单点依赖', effectiveness: '⭐⭐⭐⭐⭐' },
          { name: '本地模型兜底', desc: '部署本地开源模型（Llama / Qwen）作为降级方案', effectiveness: '⭐⭐⭐⭐' },
          { name: '抽象层封装', desc: '通过统一 API 网关封装多模型调用，业务层无感切换', effectiveness: '⭐⭐⭐⭐⭐' },
          { name: '成本监控', desc: '实时监控 API 调用量和成本，设置预算告警和自动限流', effectiveness: '⭐⭐⭐⭐' },
        ],
      },
      {
        id: 'code_quality_risk',
        name: '代码质量与安全风险',
        icon: '🐛',
        color: '#00cec9',
        severity: '🟡 中',
        desc: 'AI 生成的代码可能包含安全漏洞、逻辑错误或不符合公司编码规范，且开发者可能因过度信任而降低审查标准。',
        scenarios: [
          'AI 生成的代码包含 SQL 注入、XSS 等常见安全漏洞',
          '开发者直接采纳 AI 建议而跳过代码审查',
          'AI 生成的代码不符合公司内部编码规范和架构约定',
          'AI 引入的第三方依赖存在已知漏洞',
        ],
        realCases: [
          { date: '2024-05', event: 'Stanford 研究：使用 AI 辅助编码的开发者产出的代码安全漏洞率高 40%', impact: '因为开发者过度信任 AI 输出，降低了人工审查标准' },
          { date: '2025-01', event: 'Snyk 2025 报告：AI 生成代码中 36% 包含至少一个已知安全漏洞', impact: '企业开始在 CI/CD 中强制增加 AI 代码安全扫描步骤' },
          { date: '2025-03', event: '某公司因 AI 生成的认证代码存在逻辑漏洞，导致用户数据泄露', impact: '紧急修复 + 安全审计 + 流程整改' },
        ],
        mitigations: [
          { name: '强制安全扫描', desc: 'CI/CD 流水线中强制 SAST/DAST 扫描，AI 生成代码与人工代码同等标准', effectiveness: '⭐⭐⭐⭐⭐' },
          { name: '代码审查不降级', desc: 'AI 生成的代码必须经过与人工代码相同的 Code Review 流程', effectiveness: '⭐⭐⭐⭐⭐' },
          { name: '编码规范集成', desc: '将公司编码规范注入 AI 工具的 System Prompt / Rules 文件', effectiveness: '⭐⭐⭐⭐' },
          { name: '依赖审计', desc: 'AI 引入的新依赖必须经过安全审计和许可证检查', effectiveness: '⭐⭐⭐⭐' },
        ],
      },
      {
        id: 'social_engineering_risk',
        name: '提示注入与社工风险',
        icon: '🎭',
        color: '#636e72',
        severity: '🟡 中',
        desc: 'AI Agent 在处理外部输入时可能被提示注入攻击，执行非预期操作；员工可能被社工手段诱导泄露敏感信息。',
        scenarios: [
          'AI Agent 处理用户提交的 Issue 时，Issue 中嵌入恶意 Prompt 导致 Agent 执行危险操作',
          '攻击者在代码注释中嵌入 Prompt Injection，AI 工具读取后执行恶意指令',
          '员工被钓鱼邮件诱导，将内部代码粘贴到伪装的"AI 助手"网站',
          'AI 工具的 MCP 插件被恶意篡改，窃取传输的代码和数据',
        ],
        realCases: [
          { date: '2024-07', event: '研究者演示通过 Markdown 图片链接在 ChatGPT 中实现数据外泄', impact: 'OpenAI 紧急修复，但暴露了 AI 工具的攻击面' },
          { date: '2025-02', event: '恶意 VS Code 插件伪装为 AI 助手，窃取用户代码和 API Key', impact: 'VS Code 市场加强插件审核，企业限制插件安装权限' },
          { date: '2025-04', event: '某公司 AI Agent 被 Prompt Injection 攻击，自动执行了删除数据库的操作', impact: '紧急回滚 + 增加 Agent 操作审批机制' },
        ],
        mitigations: [
          { name: 'Agent 操作审批', desc: '高风险操作（删除/修改/部署）必须经过人工审批，Agent 不能自主执行', effectiveness: '⭐⭐⭐⭐⭐' },
          { name: '输入净化', desc: '对 AI 处理的外部输入进行 Prompt Injection 检测和净化', effectiveness: '⭐⭐⭐⭐' },
          { name: '最小权限原则', desc: 'AI 工具和 Agent 只授予完成任务所需的最小权限', effectiveness: '⭐⭐⭐⭐⭐' },
          { name: '工具链审计', desc: '定期审计 AI 工具链（插件/MCP Server/扩展）的安全性', effectiveness: '⭐⭐⭐⭐' },
        ],
      },
    ],
  },

  // 数据分级管控体系
  dataClassification: {
    title: '数据分级管控体系',
    desc: '不是所有数据都需要同等保护——按敏感度分级，差异化管控',
    levels: [
      {
        level: 'L1',
        name: '公开数据',
        icon: '🟢',
        color: '#3fb950',
        desc: '已公开或可公开的信息，无保密要求',
        examples: ['开源代码', '公开文档', '技术博客内容', '公开 API 文档', '开源依赖代码'],
        policy: '可自由使用任何外部模型，无限制',
        modelAccess: '✅ 所有外部模型',
        auditLevel: '无需审计',
      },
      {
        level: 'L2',
        name: '内部数据',
        icon: '🟡',
        color: '#ffa657',
        desc: '公司内部使用的非敏感信息，泄露不会造成重大损失',
        examples: ['内部工具代码', '非核心业务逻辑', '内部技术文档', '测试数据（已脱敏）', '内部流程文档'],
        policy: '可使用签署 ZDR 协议的外部模型 API，需脱敏处理',
        modelAccess: '✅ 签署 ZDR 的外部模型 API',
        auditLevel: '月度抽查审计',
      },
      {
        level: 'L3',
        name: '机密数据',
        icon: '🟠',
        color: '#e17055',
        desc: '核心业务代码、用户数据、商业策略等，泄露会造成重大损失',
        examples: ['核心算法代码', '用户 PII 数据', '商业策略文档', '财务数据', '客户合同信息', '内部架构设计'],
        policy: '仅可使用私有化部署的模型，或经过安全网关过滤后使用外部 API',
        modelAccess: '⚠️ 仅私有化模型 / 安全网关过滤后的外部 API',
        auditLevel: '每次使用实时审计',
      },
      {
        level: 'L4',
        name: '绝密数据',
        icon: '🔴',
        color: '#d63031',
        desc: '最高机密信息，泄露会造成不可逆的重大损失',
        examples: ['加密密钥 / 证书', '安全漏洞详情', '未公开的并购信息', '核心交易策略', '军工/国防相关数据'],
        policy: '严禁使用任何外部模型，仅限离线环境的本地模型',
        modelAccess: '❌ 禁止外部模型 / 仅离线本地模型',
        auditLevel: '全量实时审计 + 告警',
      },
    ],
  },

  // 技术管控架构
  technicalArchitecture: {
    title: '技术管控架构',
    desc: '从网络层到应用层的多层防护体系',
    layers: [
      {
        name: 'AI 安全网关层',
        icon: '🛡️',
        color: '#e17055',
        desc: '所有外部模型请求必须经过安全网关，实现统一管控',
        components: [
          { name: '敏感信息检测引擎', desc: '正则 + NER + 自定义规则，自动识别 API Key、密码、PII、内部域名等', tech: 'Presidio · Custom NER · Regex Engine' },
          { name: '自动脱敏处理', desc: '检测到敏感信息后自动替换为占位符，响应返回时还原', tech: 'Token Mapping · Reversible Masking' },
          { name: '请求审计日志', desc: '完整记录请求/响应内容、用户身份、时间戳、数据分级', tech: 'ELK · ClickHouse · 不可篡改日志' },
          { name: '策略引擎', desc: '根据数据分级、用户角色、时间窗口动态决定放行/拦截/脱敏', tech: 'OPA · Custom Policy Engine' },
        ],
      },
      {
        name: '模型路由层',
        icon: '🔀',
        color: '#6c5ce7',
        desc: '根据数据敏感度和任务类型，智能路由到最合适的模型',
        components: [
          { name: '多模型接入', desc: '统一接入 Claude / GPT / Gemini / DeepSeek / 本地 Llama 等', tech: 'LiteLLM · OpenRouter · Custom Gateway' },
          { name: '智能路由', desc: '根据数据分级自动选择模型：L1-L2 → 外部 API，L3 → 私有化，L4 → 本地离线', tech: 'Rule Engine · ML Router' },
          { name: '降级策略', desc: '外部模型不可用时自动降级到本地模型，保证可用性', tech: 'Circuit Breaker · Fallback Chain' },
          { name: '成本优化', desc: '简单任务路由到低成本模型，复杂任务路由到高能力模型', tech: 'Task Classifier · Cost Optimizer' },
        ],
      },
      {
        name: '终端管控层',
        icon: '💻',
        color: '#3fb950',
        desc: '在开发者终端（IDE / CLI / Web）层面实施管控',
        components: [
          { name: 'IDE 插件管控', desc: '统一管理 Cursor / Copilot / Continue 等 AI 插件的配置和权限', tech: 'MDM · Custom Plugin · VS Code Policy' },
          { name: '剪贴板监控', desc: '检测开发者复制敏感代码到外部 AI 工具的行为（可选，需平衡隐私）', tech: 'DLP Agent · Endpoint Protection' },
          { name: '.cursorrules 统一', desc: '通过统一的 Rules 文件注入安全规范和编码标准', tech: 'Git Template · CI Check' },
          { name: 'MCP Server 白名单', desc: '仅允许经过安全审计的 MCP Server 连接', tech: 'MCP Registry · Certificate Pinning' },
        ],
      },
      {
        name: '审计与响应层',
        icon: '📊',
        color: '#ffa657',
        desc: '持续监控、异常检测和事件响应',
        components: [
          { name: '实时仪表盘', desc: '展示 AI 工具使用量、数据分级分布、异常事件、成本趋势', tech: 'Grafana · Custom Dashboard' },
          { name: '异常检测', desc: '检测异常模式：大量代码外发、非工作时间使用、敏感数据突增', tech: 'Anomaly Detection · Alert Rules' },
          { name: '事件响应', desc: '发现安全事件后自动触发：阻断 → 通知 → 取证 → 修复 → 复盘', tech: 'SOAR · Incident Playbook' },
          { name: '合规报告', desc: '自动生成合规审计报告，满足监管要求', tech: 'Report Generator · Compliance Template' },
        ],
      },
    ],
  },

  // 模型提供商安全对比
  providerComparison: {
    title: '主流模型提供商安全能力对比',
    desc: '选择模型提供商时的安全维度评估',
    providers: [
      {
        name: 'Anthropic (Claude)',
        icon: '🟣',
        color: '#6c5ce7',
        tier: 'Tier 1',
        features: {
          zdr: '✅ 支持 API 零留存（ZDR）',
          soc2: '✅ SOC 2 Type II',
          gdpr: '✅ GDPR 合规',
          training: '✅ API 数据不用于训练（明确承诺）',
          encryption: '✅ 传输加密 TLS 1.3 + 静态加密 AES-256',
          region: '⚠️ 美国/欧洲数据中心，无中国区',
          privateDeployment: '❌ 不支持私有化部署（仅 API）',
          auditLog: '✅ 企业版支持审计日志',
        },
        verdict: '代码辅助首选，安全承诺最明确，但无私有化部署选项',
      },
      {
        name: 'OpenAI (GPT-4)',
        icon: '🟢',
        color: '#3fb950',
        tier: 'Tier 1',
        features: {
          zdr: '✅ 企业版支持 ZDR',
          soc2: '✅ SOC 2 Type II',
          gdpr: '✅ GDPR 合规',
          training: '✅ API 数据不用于训练（企业版）',
          encryption: '✅ 传输加密 TLS 1.3 + 静态加密',
          region: '⚠️ 美国/欧洲数据中心，Azure 可选更多区域',
          privateDeployment: '⚠️ Azure OpenAI 支持私有网络部署',
          auditLog: '✅ 企业版支持审计日志',
        },
        verdict: 'Azure OpenAI 是企业级首选，支持私有网络，但成本较高',
      },
      {
        name: 'Google (Gemini)',
        icon: '🔵',
        color: '#4285f4',
        tier: 'Tier 1',
        features: {
          zdr: '✅ Vertex AI 支持 ZDR',
          soc2: '✅ SOC 2 / ISO 27001',
          gdpr: '✅ GDPR 合规',
          training: '✅ API 数据不用于训练',
          encryption: '✅ Google 级加密标准',
          region: '✅ 全球多区域，含亚太',
          privateDeployment: '⚠️ Vertex AI 支持 VPC 内部署',
          auditLog: '✅ Cloud Audit Logs',
        },
        verdict: 'GCP 生态内最佳选择，多区域部署灵活',
      },
      {
        name: 'DeepSeek',
        icon: '🔷',
        color: '#0984e3',
        tier: 'Tier 2',
        features: {
          zdr: '⚠️ 需确认具体协议条款',
          soc2: '⚠️ 安全认证体系待完善',
          gdpr: '⚠️ 主要面向中国市场',
          training: '⚠️ 数据使用政策需确认',
          encryption: '✅ 传输加密',
          region: '✅ 中国境内数据中心',
          privateDeployment: '✅ 开源模型可完全私有化部署',
          auditLog: '⚠️ 需自建',
        },
        verdict: '中国合规首选，开源可私有化部署是最大优势，安全认证待加强',
      },
      {
        name: 'Qwen (通义千问)',
        icon: '🟠',
        color: '#ff6b35',
        tier: 'Tier 2',
        features: {
          zdr: '✅ 阿里云企业版支持',
          soc2: '✅ 等保三级 / ISO 27001',
          gdpr: '⚠️ 主要面向中国市场',
          training: '✅ 企业版数据不用于训练',
          encryption: '✅ 阿里云级加密标准',
          region: '✅ 中国境内多区域',
          privateDeployment: '✅ 开源模型可完全私有化部署',
          auditLog: '✅ 阿里云日志服务',
        },
        verdict: '国内企业级场景优选，阿里云生态完善，开源可私有化',
      },
    ],
    featureLabels: {
      zdr: '零数据留存 (ZDR)',
      soc2: '安全认证',
      gdpr: 'GDPR/合规',
      training: '数据不用于训练',
      encryption: '加密标准',
      region: '数据中心区域',
      privateDeployment: '私有化部署',
      auditLog: '审计日志',
    },
  },

  // 推荐方案
  recommendedApproach: {
    title: '推荐方案：分级管控 + 多模型策略',
    desc: '不是"用不用"的问题，而是"怎么用"的问题',
    phases: [
      {
        phase: 'Phase 1',
        name: '快速启用（1-2 周）',
        icon: '🚀',
        color: '#3fb950',
        actions: [
          '与 Anthropic/OpenAI 签署企业版 ZDR 协议',
          '发布《AI 工具使用安全规范 v1.0》，明确红线',
          '统一 AI 工具配置（Cursor Rules / .cursorrules），注入安全规范',
          '建立 AI 工具使用登记制度，明确谁在用、用什么、用在哪',
        ],
        deliverables: ['ZDR 协议签署', '安全规范文档', '统一配置模板'],
        risk: '低——主要是流程和规范层面',
      },
      {
        phase: 'Phase 2',
        name: '安全网关（1-2 月）',
        icon: '🛡️',
        color: '#e17055',
        actions: [
          '部署 AI 安全网关，所有外部模型请求必须经过网关',
          '实现敏感信息自动检测和脱敏（API Key / 密码 / PII / 内部域名）',
          '建立请求审计日志，支持事后追溯',
          '实现数据分级策略引擎，按 L1-L4 自动管控',
        ],
        deliverables: ['AI 安全网关 v1.0', '敏感信息检测引擎', '审计日志系统'],
        risk: '中——需要工程投入，但技术方案成熟',
      },
      {
        phase: 'Phase 3',
        name: '多模型路由（2-3 月）',
        icon: '🔀',
        color: '#6c5ce7',
        actions: [
          '部署私有化模型（DeepSeek / Qwen / Llama）处理 L3 级数据',
          '实现智能路由：根据数据分级自动选择外部/私有化/本地模型',
          '建立模型降级链：外部 → 私有化 → 本地，保证可用性',
          '成本优化：简单任务路由到低成本模型',
        ],
        deliverables: ['私有化模型部署', '智能路由引擎', '降级策略'],
        risk: '中——私有化模型部署需要 GPU 资源',
      },
      {
        phase: 'Phase 4',
        name: '持续运营（持续）',
        icon: '📊',
        color: '#ffa657',
        actions: [
          '建立 AI 安全运营仪表盘，实时监控使用情况和风险',
          '定期安全审计（月度），输出合规报告',
          '持续更新敏感信息检测规则，覆盖新场景',
          '跟踪模型提供商安全政策变化，及时调整策略',
          '定期开展 AI 安全意识培训',
        ],
        deliverables: ['安全运营仪表盘', '月度合规报告', '培训材料'],
        risk: '低——持续运营投入',
      },
    ],
  },

  // 成本效益分析
  costBenefitAnalysis: {
    title: '成本效益分析',
    desc: '"不用"的隐性成本远大于"安全地用"的显性成本',
    costs: {
      title: '安全管控成本',
      items: [
        { name: 'AI 安全网关开发', cost: '2-3 人月', type: '一次性', icon: '🛡️' },
        { name: '私有化模型部署', cost: '4-8 张 A100 GPU', type: '持续', icon: '🖥️' },
        { name: '安全运营人力', cost: '0.5-1 人', type: '持续', icon: '👤' },
        { name: '企业版 API 订阅', cost: '$5-20K/月', type: '持续', icon: '💳' },
        { name: '安全审计与合规', cost: '1-2 人月/年', type: '周期性', icon: '📋' },
      ],
    },
    benefits: {
      title: '使用外部模型的收益',
      items: [
        { name: '开发效率提升', value: '3-5x', desc: 'AI 辅助编码显著提升开发速度', icon: '⚡' },
        { name: '代码质量提升', value: '+30%', desc: 'AI 辅助 Code Review 和 Bug 检测', icon: '✅' },
        { name: '人才吸引力', value: '显著', desc: '优秀工程师期望使用最先进的 AI 工具', icon: '🧲' },
        { name: '知识传播效率', value: '5-10x', desc: 'AI 辅助文档生成、知识问答、Onboarding', icon: '📚' },
        { name: '创新速度', value: '2-3x', desc: '快速原型验证、技术方案探索', icon: '🚀' },
      ],
    },
    notUsingCosts: {
      title: '不使用外部模型的隐性成本',
      items: [
        { name: '效率差距', value: '3-5x', desc: '竞争对手使用 AI 工具后效率远超我们', icon: '📉', color: '#e17055' },
        { name: '人才流失', value: '高', desc: '优秀工程师因"工具落后"而离职', icon: '🚪', color: '#e17055' },
        { name: '招聘困难', value: '高', desc: '"不让用 AI 工具"成为候选人拒绝 Offer 的理由', icon: '❌', color: '#e17055' },
        { name: '技术债务', value: '加速', desc: '没有 AI 辅助，代码审查和重构效率低下', icon: '🏚️', color: '#ffa657' },
        { name: '创新停滞', value: '严重', desc: '无法快速验证新想法，错过市场窗口', icon: '🐌', color: '#ffa657' },
      ],
    },
  },

  // 行业实践参考
  industryPractices: {
    title: '行业实践参考',
    desc: '看看头部公司怎么做的',
    practices: [
      {
        company: 'Google',
        icon: '🔵',
        color: '#4285f4',
        approach: '内部 AI 工具为主 + 严格数据分级',
        details: [
          '内部开发 Gemini Code Assist，代码不出 Google 网络',
          '25%+ 新代码由 AI 生成（2025 Q1 财报）',
          '严格的数据分级制度，不同级别数据使用不同 AI 工具',
          '所有 AI 工具使用记录纳入安全审计',
        ],
      },
      {
        company: 'Microsoft',
        icon: '🟦',
        color: '#0078d4',
        approach: 'Azure OpenAI 私有网络 + GitHub Copilot Enterprise',
        details: [
          'Azure OpenAI 部署在企业私有网络内，数据不出 Azure 租户',
          'GitHub Copilot Enterprise 支持组织级策略管控',
          '代码建议基于组织内部代码库，减少外部数据依赖',
          'IP 赔偿承诺：如果 Copilot 生成的代码引发版权诉讼，Microsoft 承担赔偿',
        ],
      },
      {
        company: 'Stripe',
        icon: '🟣',
        color: '#635bff',
        approach: 'AI 安全网关 + 多模型策略',
        details: [
          '自建 AI Proxy，所有外部模型请求经过统一网关',
          '自动检测和脱敏 PII、API Key、内部 URL 等敏感信息',
          '按代码仓库敏感度分级，核心支付代码禁止使用外部模型',
          '内部部署开源模型处理敏感代码的辅助需求',
        ],
      },
      {
        company: 'JPMorgan',
        icon: '🏦',
        color: '#003087',
        approach: '私有化部署 + 严格合规',
        details: [
          '内部开发 LLM Suite，基于开源模型私有化部署',
          '所有 AI 工具使用需经过合规审批',
          '交易相关代码和数据严禁使用任何外部 AI 服务',
          '建立 AI 使用委员会，定期审查和更新策略',
        ],
      },
      {
        company: 'Shopify',
        icon: '🛒',
        color: '#96bf48',
        approach: '全面拥抱 + 安全护栏',
        details: [
          'CEO Tobi 要求所有员工使用 AI 工具，AI 使用纳入绩效考核',
          '但同时建立了完善的安全护栏和使用规范',
          '敏感数据自动脱敏后才能发送给外部模型',
          '定期安全培训，强调"AI 是工具，人是责任人"',
        ],
      },
    ],
  },

  // 代码生成隔离模式
  codeIsolation: {
    title: '代码生成隔离模式',
    desc: 'AI 生成代码，数据不出域——解决"AI 需要理解数据"与"数据不能离开边界"之间的根本矛盾',
    tagline: '"AI writes the code, data never leaves the perimeter"',
    corePrinciple: 'AI 只接触数据的 Schema / 元数据，生成处理代码；代码在本地/私有环境执行，真实数据全程不出域。',
    comparison: {
      traditional: {
        label: '传统模式',
        icon: '❌',
        color: '#e17055',
        steps: [
          { step: '1', text: '真实数据上传给 AI', risk: '数据泄露' },
          { step: '2', text: 'AI 分析处理数据', risk: '合规违规' },
          { step: '3', text: '返回分析结果', risk: '结果可能含敏感信息' },
        ],
      },
      isolated: {
        label: '隔离模式',
        icon: '✅',
        color: '#3fb950',
        steps: [
          { step: '1', text: 'Schema / 元数据 → AI', risk: null },
          { step: '2', text: 'AI 生成处理代码', risk: null },
          { step: '3', text: '代码在本地执行（数据不出域）', risk: null },
          { step: '4', text: '仅返回聚合结果', risk: null },
        ],
      },
    },
    terms: [
      { name: 'Code-as-Proxy', desc: 'AI 生成代码作为数据访问代理，AI 本身不碰数据', origin: 'Palantir 内部说法' },
      { name: 'Schema-Driven Code Gen', desc: '基于 Schema 而非真实数据生成代码', origin: '通用工程术语' },
      { name: 'Federated Code Execution', desc: '代码下发到数据所在地执行，数据不出域', origin: '联邦学习衍生概念' },
      { name: 'Data Residency + AI Assist', desc: '数据留存本地，AI 仅辅助生成逻辑', origin: '合规领域术语' },
      { name: 'Sandboxed Code Execution', desc: 'AI 生成代码在隔离沙箱中执行，AI 看不到原始输出', origin: '安全工程术语' },
    ],
    palantirConnection: {
      title: 'Palantir AIP 的核心安全设计',
      desc: 'AIP 中 AI 操作的是 Ontology（数据本体/Schema），而非原始数据本身。LLM 理解业务对象的结构和关系，生成操作 Ontology 的代码/动作，真实数据在 Foundry 内部执行，LLM 只看到结果摘要。',
      layers: [
        { layer: 'LLM 层', sees: 'Ontology Schema + 业务语义', color: '#6c5ce7' },
        { layer: 'AIP 层', sees: '生成操作代码 / Action', color: '#0984e3' },
        { layer: 'Foundry 层', sees: '执行代码，访问真实数据', color: '#00b894' },
        { layer: '数据层', sees: '原始数据（LLM 不可见）', color: '#636e72' },
      ],
    },
    useCases: [
      { icon: '📊', title: '数据分析', desc: 'AI 根据表结构生成 SQL/Python，在本地数据库执行，返回聚合统计' },
      { icon: '🔍', title: '数据质量检测', desc: 'AI 根据 Schema 生成数据校验规则代码，在数据仓库内执行' },
      { icon: '🤖', title: 'ML 特征工程', desc: 'AI 根据字段描述生成特征提取代码，训练数据不离开私有环境' },
      { icon: '📋', title: '合规报告', desc: 'AI 生成报告生成代码，敏感字段在本地脱敏后再输出' },
    ],
    limitations: [
      'Schema 需要足够详细才能让 AI 生成高质量代码',
      '复杂业务逻辑仍需人工审核生成的代码',
      '代码执行环境需要安全隔离，防止恶意代码注入',
      '不适用于需要 AI 直接理解数据内容的场景（如图像识别、文本分类）',
    ],
  },

  // 关键结论
  keyConclusions: {
    title: '关键结论',
    points: [
      {
        icon: '✅',
        color: '#3fb950',
        title: '必须用，但要安全地用',
        desc: '在 AI Coding 时代，不使用外部模型等于主动放弃 3-5x 的效率优势。关键是建立分级管控体系，而非一刀切禁用。',
      },
      {
        icon: '🛡️',
        color: '#e17055',
        title: '安全网关是核心基础设施',
        desc: 'AI 安全网关应该像 API Gateway 一样成为标配基础设施。所有外部模型请求必须经过网关，实现统一的检测、脱敏、审计。',
      },
      {
        icon: '🔀',
        color: '#6c5ce7',
        title: '多模型策略是必然选择',
        desc: '外部模型处理非敏感数据，私有化模型处理敏感数据，本地模型处理绝密数据。智能路由让开发者无感知。',
      },
      {
        icon: '📊',
        color: '#ffa657',
        title: '持续运营比一次性建设更重要',
        desc: '安全不是一次性项目，而是持续运营。定期审计、规则更新、培训教育、策略迭代缺一不可。',
      },
      {
        icon: '⚖️',
        color: '#00cec9',
        title: '平衡效率与安全，而非二选一',
        desc: '最好的安全策略是让开发者几乎无感知的安全策略。安全网关自动处理，开发者专注编码。',
      },
    ],
  },
};

// 8. 行业对标分析
export const BENCHMARKS = {
  title: '行业对标分析',
  companies: [
    {
      name: 'Palantir',
      model: '决策操作系统',
      icon: '🏛️',
      color: '#6c5ce7',
      strengths: ['Ontology 深度绑定', 'FDE 驻场模式', '安全合规壁垒', 'AIP 让 LLM 可操作'],
      weaknesses: ['高人力成本', '扩展速度受限', '依赖大客户'],
      takeaway: '学习 Ontology 思想和 AIP 架构，但用 AI Agent 替代 FDE 降低人力依赖',
    },
    {
      name: 'Databricks',
      model: '数据 + AI 统一平台',
      icon: '🧱',
      color: '#e17055',
      strengths: ['开源生态（Spark/Delta/MLflow）', '数据湖仓一体', 'Unity Catalog 治理', 'Mosaic AI 训练'],
      weaknesses: ['偏底层基础设施', '业务理解较浅', '与 Snowflake 竞争激烈'],
      takeaway: '学习数据平台架构和开源策略，但需要在上层补充业务语义层',
    },
    {
      name: 'Salesforce',
      model: 'CRM + AI Agent 平台',
      icon: '☁️',
      color: '#00cec9',
      strengths: ['庞大客户基础', 'Agentforce 生态', 'Data Cloud 统一', '行业解决方案'],
      weaknesses: ['平台臃肿', '定制成本高', 'AI 能力起步晚'],
      takeaway: '学习 Agent 平台化思路和行业解决方案模板，但避免平台过度复杂化',
    },
    {
      name: 'Tesla',
      model: '数据飞轮 + 端到端 AI',
      icon: '🚗',
      color: '#3fb950',
      strengths: ['百万级数据采集终端', '端到端神经网络', '数据闭环自动化', '硬件+软件垂直整合'],
      weaknesses: ['封闭生态', '高度依赖自有硬件', '安全监管风险'],
      takeaway: '学习数据飞轮和端到端思想，在自动驾驶领域直接对标',
    },
  ],
};

// ═══════════════════════════════════════════════════════════════
// 网站演进路线图 — 由 AI 设计师（角色 E）定期更新
// 最后更新：2026-04-22
// ═══════════════════════════════════════════════════════════════
export const SITE_ROADMAP = {
  lastUpdated: '2026-04-23',
  summary: '🔍 设计师第5次扫描（2026-04-23）：发现3个新高价值机会——① OpenAI Workspace Agents 开启企业自动化平台新赛道，Signal 需建立「Agent 平台」专题追踪；② Google Cloud Next \'26 全栈 AI 布局，TPU8+Agent平台+Workspace AI 三连发，云 AI 竞争格局进入新阶段；③ Qwen3.6-27B 证明「小参数密集模型」路线可行，国产开源模型专题需强化。GitHub 本周 trending 新发现：openai/openai-agents-python（多 Agent 框架）、cognee（Agent 记忆引擎）值得追踪。',

  // TOP 5 最高价值机会
  topOpportunities: [
    {
      id: 'enterprise-agent-platform',
      title: '企业 Agent 平台专题追踪（新发现）',
      priority: 'P0',
      value: '高',
      effort: '低',
      desc: 'OpenAI Workspace Agents（2026-04-22）标志着 AI 从「聊天工具」向「企业自动化平台」转型。Google Agent Platform、AWS Bedrock Agents、Microsoft Copilot Studio 三大云厂商同步发力，企业 Agent 平台正成为 2026 年最热竞争赛道。Signal 声浪 agent category 需系统化追踪这一方向。',
      action: '声浪 agent category 加强企业 Agent 平台追踪；信息源加入 OpenAI 企业博客 + Google Cloud Blog；考虑在工具箱新增「企业 Agent 平台对比」Tab',
      color: '#6c5ce7',
    },
    {
      id: 'google-cloud-ai-fullstack',
      title: 'Google 全栈 AI 竞争格局专题',
      priority: 'P0',
      value: '高',
      effort: '低',
      desc: 'Google Cloud Next \'26 展示了从 TPU8（芯片）→ Gemini（模型）→ Agent Platform（平台）→ Workspace AI（应用）的完整全栈布局，与 Microsoft Azure+Copilot 的竞争格局进入新阶段。Signal 对 Google Cloud 方向的覆盖相对薄弱，需要加强。',
      action: '声浪 infra category 加强 Google Cloud 追踪；信息源加入 Google Cloud Blog；考虑在模型中心新增 Google TPU 系列对比',
      color: '#00b894',
    },
    {
      id: 'china-opensource-models',
      title: '国产开源模型专题强化',
      priority: 'P0',
      value: '高',
      effort: '中',
      desc: 'Qwen3.6-27B（2026-04-22）证明国产开源模型在 Agent 编程场景的竞争力，超越 397B MoE。Qwen 系列、DeepSeek 系列、InternLM 系列持续迭代，国产开源模型已进入全球第一梯队。Signal 声浪 llm category 对国产模型的覆盖需要系统化。',
      action: '声浪 llm category 加强国产开源模型追踪；信息源加入 Qwen Blog（qwenlm.github.io）+ 智源研究院；模型库优先补充 Qwen3 系列最新版本',
      color: '#fd79a8',
    },
    {
      id: 'ai-safety-coverage',
      title: 'AI 安全/对齐专题 ✅',
      priority: 'P0',
      value: '高',
      effort: '中',
      desc: '✅ 已实施（2026-04-22）：声浪 safety category 新增 Anthropic Mythos 事件（NSA 使用/未授权访问/Altman 评论）+ Meta 员工键盘记录训练 AI 两条高质量内容。MCP 协议 RCE 漏洞（11个CVE）也已覆盖。',
      action: '持续更新：关注 Anthropic 安全博客 / AI Safety Institute / METR，每周补充 1-2 条',
      color: '#00b894',
    },
    {
      id: 'agent-memory-infra',
      title: 'Agent 记忆与知识引擎新兴生态',
      priority: 'P1',
      value: '高',
      effort: '中',
      desc: 'GitHub trending 发现 cognee（Agent 记忆引擎，"6行代码实现 Agent 记忆"）、openai/openai-agents-python（多 Agent 框架）等新兴工具快速崛起。Agent 记忆/知识管理是 2026 年 Agent 基础设施的核心缺口，Signal 完全缺失该方向。',
      action: '声浪 agent category 新增 Agent 记忆/知识引擎方向；工具箱考虑新增「Agent 基础设施」Tab，覆盖 cognee/mem0/Zep 等工具',
      color: '#ffa657',
    },
  ],

  // GitHub 明星资源发现
  githubFindings: [
    {
      repo: 'openai/openai-agents-python',
      stars: '10k+',
      type: 'Agent 框架',
      priority: 'P0',
      reason: 'OpenAI 官方多 Agent 框架，与 Workspace Agents 配套，Signal 完全缺失该方向',
      action: '声浪 agent category 追踪 + 工具箱 Agent 框架对比',
    },
    {
      repo: 'topoteretes/cognee',
      stars: '5k+',
      type: 'Agent 记忆引擎',
      priority: 'P0',
      reason: '6行代码实现 Agent 知识图谱记忆，GitHub trending 本周爆火，Signal 完全缺失',
      action: '声浪 agent category 追踪 + 工具箱新增 Agent 记忆工具分类',
    },
    {
      repo: 'microsoft/markitdown',
      stars: '40k+',
      type: '文档处理工具',
      priority: 'P1',
      reason: '将各类文档转为 Markdown，是 RAG/Agent 数据预处理的重要工具，Signal 未覆盖',
      action: '声浪 infra category 追踪 + 工具箱 RAG 工具分类',
    },
    {
      repo: 'modelcontextprotocol/servers',
      stars: '14k+',
      type: 'MCP 生态',
      priority: 'P0',
      reason: 'MCP 协议官方 Server 集合，Signal 完全缺失该方向',
      action: '新增信息源白名单 + 专题目录',
    },
    {
      repo: 'LLaMA-Factory',
      stars: '40k+',
      type: '训练框架',
      priority: 'P1',
      reason: '最流行的开源微调框架，声浪 infra category 覆盖不足',
      action: '声浪 infra 补充相关动态',
    },
  ],

  // 新闻角度盲区
  coverageGaps: [
    { angle: '企业 Agent 平台竞争', severity: '严重缺失', hotness: '🔥🔥🔥', suggestedCategory: 'agent', suggestedSources: ['OpenAI 企业博客', 'Google Cloud Blog', 'AWS Bedrock Blog', 'Microsoft Copilot Studio Blog'] },
    { angle: 'Agent 记忆/知识引擎', severity: '严重缺失', hotness: '🔥🔥🔥', suggestedCategory: 'agent', suggestedSources: ['cognee GitHub', 'mem0 Blog', 'Zep Blog'] },
    { angle: '国产开源模型进展', severity: '覆盖不足', hotness: '🔥🔥🔥', suggestedCategory: 'llm', suggestedSources: ['qwenlm.github.io', '智源研究院', '上海AI实验室'] },
    { angle: 'AI 编程工具', severity: '已覆盖 ✅', hotness: '🔥🔥🔥', suggestedCategory: 'coding', suggestedSources: ['Cursor Blog', 'GitHub Blog', 'Cognition AI'] },
    { angle: 'AI 安全/对齐', severity: '已覆盖 ✅', hotness: '🔥🔥🔥', suggestedCategory: 'safety', suggestedSources: ['Anthropic 安全博客', 'AI Safety Institute', 'METR'] },
    { angle: '端侧/小模型', severity: '覆盖不足', hotness: '🔥🔥', suggestedCategory: 'infra', suggestedSources: ['Microsoft Research', 'Google', 'Apple ML Research'] },
    { angle: 'AI 硬件/芯片', severity: '覆盖不足', hotness: '🔥🔥', suggestedCategory: 'infra', suggestedSources: ['Groq', 'Cerebras', '寒武纪官网'] },
    { angle: 'AI + 医疗', severity: '覆盖不足', hotness: '🔥🔥', suggestedCategory: 'industry', suggestedSources: ['DeepMind Blog', 'Nature', 'NEJM'] },
    { angle: '欧洲 AI 生态', severity: '覆盖不足', hotness: '🔥', suggestedCategory: 'industry', suggestedSources: ['Mistral Blog', 'EU AI Office'] },
  ],

  // 模块扩充建议
  moduleProposals: [
    {
      name: '企业 Agent 平台对比',
      type: '工具/实践类',
      priority: 'P0',
      effort: '中',
      value: '高',
      desc: 'OpenAI Workspace Agents vs Google Agent Platform vs AWS Bedrock Agents vs Microsoft Copilot Studio 横向对比，2026 年最热竞争赛道',
      dataSource: '各平台官方文档 + 社区评测',
      implementHint: '工具箱新增「企业 Agent 平台」Tab，参考 AI 编程工具对比矩阵的实现方式',
    },
    {
      name: 'Agent 基础设施工具目录',
      type: '工具/实践类',
      priority: 'P0',
      effort: '低',
      value: '高',
      desc: '覆盖 Agent 记忆（cognee/mem0/Zep）、Agent 框架（openai-agents/LangGraph/CrewAI）、Agent 评测（AgentBench）等新兴工具生态',
      dataSource: 'GitHub trending + 各工具官网',
      implementHint: '工具箱新增「Agent 基础设施」分类，或在现有 MCP 目录下扩展',
    },
    {
      name: 'MCP Server 目录',
      type: '工具/实践类',
      priority: 'P0',
      effort: '低',
      value: '高',
      desc: '追踪 modelcontextprotocol/servers 生态，分类展示可用的 MCP 工具',
      dataSource: 'github.com/modelcontextprotocol/servers',
      implementHint: '在现有「工具」页面下新增 MCP 分类，或独立新页面',
    },
    {
      name: 'GitHub Trending 追踪',
      type: '社区/动态类',
      priority: 'P0',
      effort: '低',
      value: '高',
      desc: '每日更新 AI 相关仓库的 trending 情况',
      dataSource: 'github.com/trending',
      implementHint: '声浪新增 github category，采集员每日抓取',
    },
    {
      name: 'HF 每日论文',
      type: '学术/研究类',
      priority: 'P0',
      effort: '低',
      value: '高',
      desc: '追踪 Hugging Face 每日精选论文',
      dataSource: 'huggingface.co/papers',
      implementHint: '论文模块新增「HF 精选」标签，采集员加入该来源',
    },
    {
      name: 'AI 工具对比矩阵',
      type: '工具/实践类',
      priority: 'P1',
      effort: '中',
      value: '高',
      desc: 'Cursor vs Copilot vs Windsurf vs Devin 等编程工具横向对比',
      dataSource: '各工具官网 + 社区评测',
      implementHint: '「工具」页面新增对比矩阵组件',
    },
    {
      name: 'AI 能力进化时间线',
      type: '数据看板类',
      priority: 'P1',
      effort: '中',
      value: '高',
      desc: '以时间轴形式展示各模型在各 Benchmark 上的历史进展',
      dataSource: 'Papers with Code / LMSYS Arena',
      implementHint: '评测榜页面扩展，增加历史趋势视图',
    },
    {
      name: 'Prompt 工程库',
      type: '工具/实践类',
      priority: 'P1',
      effort: '低',
      value: '高',
      desc: '收录高质量 System Prompt / Few-shot 示例',
      dataSource: 'GitHub awesome-prompts / 社区贡献',
      implementHint: '新增独立页面，支持分类浏览和搜索',
    },
    {
      name: 'AI 术语词典',
      type: '知识沉淀类',
      priority: 'P2',
      effort: '低',
      value: '中',
      desc: 'MoE / GQA / KV Cache / RLHF / DPO 等专业术语解释',
      dataSource: '论文 + 技术博客',
      implementHint: '新增词典页面，SEO 友好',
    },
  ],

  // 建议新增信息源
  suggestedSources: [
    { name: 'Google Cloud Blog', url: 'https://cloud.google.com/blog/products/ai-machine-learning', type: '企业博客', reason: 'Google Cloud Next \'26 后，Google Cloud AI 动态值得系统追踪' },
    { name: 'OpenAI 企业博客', url: 'https://openai.com/enterprise', type: '企业博客', reason: 'Workspace Agents 等企业产品的一手信息来源' },
    { name: 'Qwen Blog', url: 'https://qwenlm.github.io/blog/', type: '模型博客', reason: 'Qwen3 系列持续迭代，国产开源模型一手信息' },
    { name: 'Hugging Face Daily Papers', url: 'https://huggingface.co/papers', type: '论文聚合', reason: '每日精选 arXiv 论文，质量高' },
    { name: 'Lilian Weng Blog', url: 'https://lilianweng.github.io/', type: '个人博客', reason: 'OpenAI 研究员，综述质量极高' },
    { name: 'vLLM Blog', url: 'https://blog.vllm.ai/', type: '工程博客', reason: '推理框架最新进展' },
    { name: 'Last Week in AI', url: 'https://lastweekin.ai/', type: 'Newsletter', reason: '每周 AI 动态汇总，覆盖面广' },
    { name: 'Import AI', url: 'https://jack-clark.net/', type: 'Newsletter', reason: 'Jack Clark（Anthropic 联创）周报' },
    { name: '智源研究院', url: 'https://www.baai.ac.cn/news.html', type: '学术机构', reason: 'FlagAI / BGE 等开源项目' },
    { name: '上海 AI 实验室', url: 'https://www.shlab.org.cn/', type: '学术机构', reason: 'InternLM / OpenCompass' },
    { name: 'LangChain Blog', url: 'https://blog.langchain.dev/', type: '工程博客', reason: 'Agent 框架动态' },
  ],
};